//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSAR.SchoolYearServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SchoolYear", Namespace="http://schemas.datacontract.org/2004/07/eSARService")]
    [System.SerializableAttribute()]
    public partial class SchoolYear : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CurrentSYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SYField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CurrentSY {
            get {
                return this.CurrentSYField;
            }
            set {
                if ((this.CurrentSYField.Equals(value) != true)) {
                    this.CurrentSYField = value;
                    this.RaisePropertyChanged("CurrentSY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SY {
            get {
                return this.SYField;
            }
            set {
                if ((object.ReferenceEquals(this.SYField, value) != true)) {
                    this.SYField = value;
                    this.RaisePropertyChanged("SY");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SchoolYearServiceRef.ISchoolYearService")]
    public interface ISchoolYearService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolYearService/GetSY", ReplyAction="http://tempuri.org/ISchoolYearService/GetSYResponse")]
        eSAR.SchoolYearServiceRef.SchoolYear GetSY(string schoolyear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolYearService/GetSY", ReplyAction="http://tempuri.org/ISchoolYearService/GetSYResponse")]
        System.Threading.Tasks.Task<eSAR.SchoolYearServiceRef.SchoolYear> GetSYAsync(string schoolyear);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolYearService/CreateSY", ReplyAction="http://tempuri.org/ISchoolYearService/CreateSYResponse")]
        eSAR.SchoolYearServiceRef.CreateSYResponse CreateSY(eSAR.SchoolYearServiceRef.CreateSYRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolYearService/CreateSY", ReplyAction="http://tempuri.org/ISchoolYearService/CreateSYResponse")]
        System.Threading.Tasks.Task<eSAR.SchoolYearServiceRef.CreateSYResponse> CreateSYAsync(eSAR.SchoolYearServiceRef.CreateSYRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolYearService/UpdateSY", ReplyAction="http://tempuri.org/ISchoolYearService/UpdateSYResponse")]
        eSAR.SchoolYearServiceRef.UpdateSYResponse UpdateSY(eSAR.SchoolYearServiceRef.UpdateSYRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolYearService/UpdateSY", ReplyAction="http://tempuri.org/ISchoolYearService/UpdateSYResponse")]
        System.Threading.Tasks.Task<eSAR.SchoolYearServiceRef.UpdateSYResponse> UpdateSYAsync(eSAR.SchoolYearServiceRef.UpdateSYRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolYearService/GetAllSY", ReplyAction="http://tempuri.org/ISchoolYearService/GetAllSYResponse")]
        eSAR.SchoolYearServiceRef.SchoolYear[] GetAllSY();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolYearService/GetAllSY", ReplyAction="http://tempuri.org/ISchoolYearService/GetAllSYResponse")]
        System.Threading.Tasks.Task<eSAR.SchoolYearServiceRef.SchoolYear[]> GetAllSYAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolYearService/DeleteSY", ReplyAction="http://tempuri.org/ISchoolYearService/DeleteSYResponse")]
        eSAR.SchoolYearServiceRef.DeleteSYResponse DeleteSY(eSAR.SchoolYearServiceRef.DeleteSYRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISchoolYearService/DeleteSY", ReplyAction="http://tempuri.org/ISchoolYearService/DeleteSYResponse")]
        System.Threading.Tasks.Task<eSAR.SchoolYearServiceRef.DeleteSYResponse> DeleteSYAsync(eSAR.SchoolYearServiceRef.DeleteSYRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateSY", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateSYRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public eSAR.SchoolYearServiceRef.SchoolYear schoolyear;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public CreateSYRequest() {
        }
        
        public CreateSYRequest(eSAR.SchoolYearServiceRef.SchoolYear schoolyear, string message) {
            this.schoolyear = schoolyear;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateSYResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateSYResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CreateSYResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public eSAR.SchoolYearServiceRef.SchoolYear schoolyear;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string message;
        
        public CreateSYResponse() {
        }
        
        public CreateSYResponse(bool CreateSYResult, eSAR.SchoolYearServiceRef.SchoolYear schoolyear, string message) {
            this.CreateSYResult = CreateSYResult;
            this.schoolyear = schoolyear;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateSY", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateSYRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public eSAR.SchoolYearServiceRef.SchoolYear schoolyear;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public UpdateSYRequest() {
        }
        
        public UpdateSYRequest(eSAR.SchoolYearServiceRef.SchoolYear schoolyear, string message) {
            this.schoolyear = schoolyear;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateSYResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateSYResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UpdateSYResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public eSAR.SchoolYearServiceRef.SchoolYear schoolyear;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string message;
        
        public UpdateSYResponse() {
        }
        
        public UpdateSYResponse(bool UpdateSYResult, eSAR.SchoolYearServiceRef.SchoolYear schoolyear, string message) {
            this.UpdateSYResult = UpdateSYResult;
            this.schoolyear = schoolyear;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteSY", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteSYRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string schoolyear;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public DeleteSYRequest() {
        }
        
        public DeleteSYRequest(string schoolyear, string message) {
            this.schoolyear = schoolyear;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteSYResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteSYResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DeleteSYResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public DeleteSYResponse() {
        }
        
        public DeleteSYResponse(bool DeleteSYResult, string message) {
            this.DeleteSYResult = DeleteSYResult;
            this.message = message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISchoolYearServiceChannel : eSAR.SchoolYearServiceRef.ISchoolYearService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SchoolYearServiceClient : System.ServiceModel.ClientBase<eSAR.SchoolYearServiceRef.ISchoolYearService>, eSAR.SchoolYearServiceRef.ISchoolYearService {
        
        public SchoolYearServiceClient() {
        }
        
        public SchoolYearServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SchoolYearServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchoolYearServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchoolYearServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public eSAR.SchoolYearServiceRef.SchoolYear GetSY(string schoolyear) {
            return base.Channel.GetSY(schoolyear);
        }
        
        public System.Threading.Tasks.Task<eSAR.SchoolYearServiceRef.SchoolYear> GetSYAsync(string schoolyear) {
            return base.Channel.GetSYAsync(schoolyear);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSAR.SchoolYearServiceRef.CreateSYResponse eSAR.SchoolYearServiceRef.ISchoolYearService.CreateSY(eSAR.SchoolYearServiceRef.CreateSYRequest request) {
            return base.Channel.CreateSY(request);
        }
        
        public bool CreateSY(ref eSAR.SchoolYearServiceRef.SchoolYear schoolyear, ref string message) {
            eSAR.SchoolYearServiceRef.CreateSYRequest inValue = new eSAR.SchoolYearServiceRef.CreateSYRequest();
            inValue.schoolyear = schoolyear;
            inValue.message = message;
            eSAR.SchoolYearServiceRef.CreateSYResponse retVal = ((eSAR.SchoolYearServiceRef.ISchoolYearService)(this)).CreateSY(inValue);
            schoolyear = retVal.schoolyear;
            message = retVal.message;
            return retVal.CreateSYResult;
        }
        
        public System.Threading.Tasks.Task<eSAR.SchoolYearServiceRef.CreateSYResponse> CreateSYAsync(eSAR.SchoolYearServiceRef.CreateSYRequest request) {
            return base.Channel.CreateSYAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSAR.SchoolYearServiceRef.UpdateSYResponse eSAR.SchoolYearServiceRef.ISchoolYearService.UpdateSY(eSAR.SchoolYearServiceRef.UpdateSYRequest request) {
            return base.Channel.UpdateSY(request);
        }
        
        public bool UpdateSY(ref eSAR.SchoolYearServiceRef.SchoolYear schoolyear, ref string message) {
            eSAR.SchoolYearServiceRef.UpdateSYRequest inValue = new eSAR.SchoolYearServiceRef.UpdateSYRequest();
            inValue.schoolyear = schoolyear;
            inValue.message = message;
            eSAR.SchoolYearServiceRef.UpdateSYResponse retVal = ((eSAR.SchoolYearServiceRef.ISchoolYearService)(this)).UpdateSY(inValue);
            schoolyear = retVal.schoolyear;
            message = retVal.message;
            return retVal.UpdateSYResult;
        }
        
        public System.Threading.Tasks.Task<eSAR.SchoolYearServiceRef.UpdateSYResponse> UpdateSYAsync(eSAR.SchoolYearServiceRef.UpdateSYRequest request) {
            return base.Channel.UpdateSYAsync(request);
        }
        
        public eSAR.SchoolYearServiceRef.SchoolYear[] GetAllSY() {
            return base.Channel.GetAllSY();
        }
        
        public System.Threading.Tasks.Task<eSAR.SchoolYearServiceRef.SchoolYear[]> GetAllSYAsync() {
            return base.Channel.GetAllSYAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSAR.SchoolYearServiceRef.DeleteSYResponse eSAR.SchoolYearServiceRef.ISchoolYearService.DeleteSY(eSAR.SchoolYearServiceRef.DeleteSYRequest request) {
            return base.Channel.DeleteSY(request);
        }
        
        public bool DeleteSY(string schoolyear, ref string message) {
            eSAR.SchoolYearServiceRef.DeleteSYRequest inValue = new eSAR.SchoolYearServiceRef.DeleteSYRequest();
            inValue.schoolyear = schoolyear;
            inValue.message = message;
            eSAR.SchoolYearServiceRef.DeleteSYResponse retVal = ((eSAR.SchoolYearServiceRef.ISchoolYearService)(this)).DeleteSY(inValue);
            message = retVal.message;
            return retVal.DeleteSYResult;
        }
        
        public System.Threading.Tasks.Task<eSAR.SchoolYearServiceRef.DeleteSYResponse> DeleteSYAsync(eSAR.SchoolYearServiceRef.DeleteSYRequest request) {
            return base.Channel.DeleteSYAsync(request);
        }
    }
}
