//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSAR.CurriculumServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GradeLevel", Namespace="http://schemas.datacontract.org/2004/07/eSARService")]
    [System.SerializableAttribute()]
    public partial class GradeLevel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradeLevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eSAR.CurriculumServiceRef.Fee[] StudentFeesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eSAR.CurriculumServiceRef.Trait[] TraitsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GradeLev {
            get {
                return this.GradeLevField;
            }
            set {
                if ((object.ReferenceEquals(this.GradeLevField, value) != true)) {
                    this.GradeLevField = value;
                    this.RaisePropertyChanged("GradeLev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eSAR.CurriculumServiceRef.Fee[] StudentFees {
            get {
                return this.StudentFeesField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentFeesField, value) != true)) {
                    this.StudentFeesField = value;
                    this.RaisePropertyChanged("StudentFees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eSAR.CurriculumServiceRef.Trait[] Traits {
            get {
                return this.TraitsField;
            }
            set {
                if ((object.ReferenceEquals(this.TraitsField, value) != true)) {
                    this.TraitsField = value;
                    this.RaisePropertyChanged("Traits");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fee", Namespace="http://schemas.datacontract.org/2004/07/eSARService")]
    [System.SerializableAttribute()]
    public partial class Fee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeactivatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FeeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FeeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradeLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SYImplementedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateSet {
            get {
                return this.DateSetField;
            }
            set {
                if ((this.DateSetField.Equals(value) != true)) {
                    this.DateSetField = value;
                    this.RaisePropertyChanged("DateSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deactivated {
            get {
                return this.DeactivatedField;
            }
            set {
                if ((this.DeactivatedField.Equals(value) != true)) {
                    this.DeactivatedField = value;
                    this.RaisePropertyChanged("Deactivated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FeeCode {
            get {
                return this.FeeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FeeCodeField, value) != true)) {
                    this.FeeCodeField = value;
                    this.RaisePropertyChanged("FeeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FeeDescription {
            get {
                return this.FeeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.FeeDescriptionField, value) != true)) {
                    this.FeeDescriptionField = value;
                    this.RaisePropertyChanged("FeeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GradeLevel {
            get {
                return this.GradeLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.GradeLevelField, value) != true)) {
                    this.GradeLevelField = value;
                    this.RaisePropertyChanged("GradeLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SYImplemented {
            get {
                return this.SYImplementedField;
            }
            set {
                if ((object.ReferenceEquals(this.SYImplementedField, value) != true)) {
                    this.SYImplementedField = value;
                    this.RaisePropertyChanged("SYImplemented");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Trait", Namespace="http://schemas.datacontract.org/2004/07/eSARService")]
    [System.SerializableAttribute()]
    public partial class Trait : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradeLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TraitCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GradeLevel {
            get {
                return this.GradeLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.GradeLevelField, value) != true)) {
                    this.GradeLevelField = value;
                    this.RaisePropertyChanged("GradeLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TraitCode {
            get {
                return this.TraitCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TraitCodeField, value) != true)) {
                    this.TraitCodeField = value;
                    this.RaisePropertyChanged("TraitCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Curriculum", Namespace="http://schemas.datacontract.org/2004/07/eSARService")]
    [System.SerializableAttribute()]
    public partial class Curriculum : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CurrentCurrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurriculumCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eSAR.CurriculumServiceRef.CurriculumSubject[] CurriculumSubjectsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CurrentCurr {
            get {
                return this.CurrentCurrField;
            }
            set {
                if ((this.CurrentCurrField.Equals(value) != true)) {
                    this.CurrentCurrField = value;
                    this.RaisePropertyChanged("CurrentCurr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurriculumCode {
            get {
                return this.CurriculumCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CurriculumCodeField, value) != true)) {
                    this.CurriculumCodeField = value;
                    this.RaisePropertyChanged("CurriculumCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eSAR.CurriculumServiceRef.CurriculumSubject[] CurriculumSubjects {
            get {
                return this.CurriculumSubjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.CurriculumSubjectsField, value) != true)) {
                    this.CurriculumSubjectsField = value;
                    this.RaisePropertyChanged("CurriculumSubjects");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CurriculumSubject", Namespace="http://schemas.datacontract.org/2004/07/eSARService")]
    [System.SerializableAttribute()]
    public partial class CurriculumSubject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> AcademicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrSubCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CurrentCurrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurriculumCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeactivatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradeLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LearningAreaCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> RatePerUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eSAR.CurriculumServiceRef.Subject SubjField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> UnitsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Academic {
            get {
                return this.AcademicField;
            }
            set {
                if ((this.AcademicField.Equals(value) != true)) {
                    this.AcademicField = value;
                    this.RaisePropertyChanged("Academic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrDescription {
            get {
                return this.CurrDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrDescriptionField, value) != true)) {
                    this.CurrDescriptionField = value;
                    this.RaisePropertyChanged("CurrDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrSubCode {
            get {
                return this.CurrSubCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrSubCodeField, value) != true)) {
                    this.CurrSubCodeField = value;
                    this.RaisePropertyChanged("CurrSubCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CurrentCurr {
            get {
                return this.CurrentCurrField;
            }
            set {
                if ((this.CurrentCurrField.Equals(value) != true)) {
                    this.CurrentCurrField = value;
                    this.RaisePropertyChanged("CurrentCurr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurriculumCode {
            get {
                return this.CurriculumCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CurriculumCodeField, value) != true)) {
                    this.CurriculumCodeField = value;
                    this.RaisePropertyChanged("CurriculumCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deactivated {
            get {
                return this.DeactivatedField;
            }
            set {
                if ((this.DeactivatedField.Equals(value) != true)) {
                    this.DeactivatedField = value;
                    this.RaisePropertyChanged("Deactivated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GradeLevel {
            get {
                return this.GradeLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.GradeLevelField, value) != true)) {
                    this.GradeLevelField = value;
                    this.RaisePropertyChanged("GradeLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LearningAreaCode {
            get {
                return this.LearningAreaCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LearningAreaCodeField, value) != true)) {
                    this.LearningAreaCodeField = value;
                    this.RaisePropertyChanged("LearningAreaCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> RatePerUnit {
            get {
                return this.RatePerUnitField;
            }
            set {
                if ((this.RatePerUnitField.Equals(value) != true)) {
                    this.RatePerUnitField = value;
                    this.RaisePropertyChanged("RatePerUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eSAR.CurriculumServiceRef.Subject Subj {
            get {
                return this.SubjField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjField, value) != true)) {
                    this.SubjField = value;
                    this.RaisePropertyChanged("Subj");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubjectCode {
            get {
                return this.SubjectCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectCodeField, value) != true)) {
                    this.SubjectCodeField = value;
                    this.RaisePropertyChanged("SubjectCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubjectDescription {
            get {
                return this.SubjectDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectDescriptionField, value) != true)) {
                    this.SubjectDescriptionField = value;
                    this.RaisePropertyChanged("SubjectDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Units {
            get {
                return this.UnitsField;
            }
            set {
                if ((this.UnitsField.Equals(value) != true)) {
                    this.UnitsField = value;
                    this.RaisePropertyChanged("Units");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Subject", Namespace="http://schemas.datacontract.org/2004/07/eSARService")]
    [System.SerializableAttribute()]
    public partial class Subject : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradeLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eSAR.CurriculumServiceRef.LearningArea LAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LearningAreaCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubjectCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GradeLevel {
            get {
                return this.GradeLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.GradeLevelField, value) != true)) {
                    this.GradeLevelField = value;
                    this.RaisePropertyChanged("GradeLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eSAR.CurriculumServiceRef.LearningArea LArea {
            get {
                return this.LAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.LAreaField, value) != true)) {
                    this.LAreaField = value;
                    this.RaisePropertyChanged("LArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LearningAreaCode {
            get {
                return this.LearningAreaCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LearningAreaCodeField, value) != true)) {
                    this.LearningAreaCodeField = value;
                    this.RaisePropertyChanged("LearningAreaCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubjectCode {
            get {
                return this.SubjectCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectCodeField, value) != true)) {
                    this.SubjectCodeField = value;
                    this.RaisePropertyChanged("SubjectCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LearningArea", Namespace="http://schemas.datacontract.org/2004/07/eSARService")]
    [System.SerializableAttribute()]
    public partial class LearningArea : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> AcademicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LearningAreaCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> RatePerUnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eSAR.CurriculumServiceRef.Subject[] SubjectsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> UnitsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Academic {
            get {
                return this.AcademicField;
            }
            set {
                if ((this.AcademicField.Equals(value) != true)) {
                    this.AcademicField = value;
                    this.RaisePropertyChanged("Academic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LearningAreaCode {
            get {
                return this.LearningAreaCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LearningAreaCodeField, value) != true)) {
                    this.LearningAreaCodeField = value;
                    this.RaisePropertyChanged("LearningAreaCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> RatePerUnit {
            get {
                return this.RatePerUnitField;
            }
            set {
                if ((this.RatePerUnitField.Equals(value) != true)) {
                    this.RatePerUnitField = value;
                    this.RaisePropertyChanged("RatePerUnit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eSAR.CurriculumServiceRef.Subject[] Subjects {
            get {
                return this.SubjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.SubjectsField, value) != true)) {
                    this.SubjectsField = value;
                    this.RaisePropertyChanged("Subjects");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Units {
            get {
                return this.UnitsField;
            }
            set {
                if ((this.UnitsField.Equals(value) != true)) {
                    this.UnitsField = value;
                    this.RaisePropertyChanged("Units");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CurriculumServiceRef.ICurriculumService")]
    public interface ICurriculumService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurriculumService/GetAllGradeLevels", ReplyAction="http://tempuri.org/ICurriculumService/GetAllGradeLevelsResponse")]
        eSAR.CurriculumServiceRef.GradeLevel[] GetAllGradeLevels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurriculumService/GetAllGradeLevels", ReplyAction="http://tempuri.org/ICurriculumService/GetAllGradeLevelsResponse")]
        System.Threading.Tasks.Task<eSAR.CurriculumServiceRef.GradeLevel[]> GetAllGradeLevelsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurriculumService/UpdateCurriculum", ReplyAction="http://tempuri.org/ICurriculumService/UpdateCurriculumResponse")]
        eSAR.CurriculumServiceRef.UpdateCurriculumResponse UpdateCurriculum(eSAR.CurriculumServiceRef.UpdateCurriculumRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurriculumService/UpdateCurriculum", ReplyAction="http://tempuri.org/ICurriculumService/UpdateCurriculumResponse")]
        System.Threading.Tasks.Task<eSAR.CurriculumServiceRef.UpdateCurriculumResponse> UpdateCurriculumAsync(eSAR.CurriculumServiceRef.UpdateCurriculumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurriculumService/CreateCurriculum", ReplyAction="http://tempuri.org/ICurriculumService/CreateCurriculumResponse")]
        eSAR.CurriculumServiceRef.CreateCurriculumResponse CreateCurriculum(eSAR.CurriculumServiceRef.CreateCurriculumRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurriculumService/CreateCurriculum", ReplyAction="http://tempuri.org/ICurriculumService/CreateCurriculumResponse")]
        System.Threading.Tasks.Task<eSAR.CurriculumServiceRef.CreateCurriculumResponse> CreateCurriculumAsync(eSAR.CurriculumServiceRef.CreateCurriculumRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurriculumService/GetAllCurriculums", ReplyAction="http://tempuri.org/ICurriculumService/GetAllCurriculumsResponse")]
        eSAR.CurriculumServiceRef.Curriculum[] GetAllCurriculums();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurriculumService/GetAllCurriculums", ReplyAction="http://tempuri.org/ICurriculumService/GetAllCurriculumsResponse")]
        System.Threading.Tasks.Task<eSAR.CurriculumServiceRef.Curriculum[]> GetAllCurriculumsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurriculumService/GetCurriculumSubjects", ReplyAction="http://tempuri.org/ICurriculumService/GetCurriculumSubjectsResponse")]
        eSAR.CurriculumServiceRef.CurriculumSubject[] GetCurriculumSubjects(string curriculumCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurriculumService/GetCurriculumSubjects", ReplyAction="http://tempuri.org/ICurriculumService/GetCurriculumSubjectsResponse")]
        System.Threading.Tasks.Task<eSAR.CurriculumServiceRef.CurriculumSubject[]> GetCurriculumSubjectsAsync(string curriculumCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurriculumService/GetAllSubjectDetails", ReplyAction="http://tempuri.org/ICurriculumService/GetAllSubjectDetailsResponse")]
        eSAR.CurriculumServiceRef.CurriculumSubject[] GetAllSubjectDetails();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurriculumService/GetAllSubjectDetails", ReplyAction="http://tempuri.org/ICurriculumService/GetAllSubjectDetailsResponse")]
        System.Threading.Tasks.Task<eSAR.CurriculumServiceRef.CurriculumSubject[]> GetAllSubjectDetailsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurriculumService/GetAllSubjectsOfGradeLevel", ReplyAction="http://tempuri.org/ICurriculumService/GetAllSubjectsOfGradeLevelResponse")]
        eSAR.CurriculumServiceRef.CurriculumSubject[] GetAllSubjectsOfGradeLevel(string gradeLevel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICurriculumService/GetAllSubjectsOfGradeLevel", ReplyAction="http://tempuri.org/ICurriculumService/GetAllSubjectsOfGradeLevelResponse")]
        System.Threading.Tasks.Task<eSAR.CurriculumServiceRef.CurriculumSubject[]> GetAllSubjectsOfGradeLevelAsync(string gradeLevel);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCurriculum", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateCurriculumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public eSAR.CurriculumServiceRef.Curriculum curriculum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public UpdateCurriculumRequest() {
        }
        
        public UpdateCurriculumRequest(eSAR.CurriculumServiceRef.Curriculum curriculum, string message) {
            this.curriculum = curriculum;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateCurriculumResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateCurriculumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UpdateCurriculumResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public eSAR.CurriculumServiceRef.Curriculum curriculum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string message;
        
        public UpdateCurriculumResponse() {
        }
        
        public UpdateCurriculumResponse(bool UpdateCurriculumResult, eSAR.CurriculumServiceRef.Curriculum curriculum, string message) {
            this.UpdateCurriculumResult = UpdateCurriculumResult;
            this.curriculum = curriculum;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateCurriculum", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateCurriculumRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public eSAR.CurriculumServiceRef.Curriculum curriculum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public CreateCurriculumRequest() {
        }
        
        public CreateCurriculumRequest(eSAR.CurriculumServiceRef.Curriculum curriculum, string message) {
            this.curriculum = curriculum;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateCurriculumResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateCurriculumResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CreateCurriculumResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public eSAR.CurriculumServiceRef.Curriculum curriculum;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string message;
        
        public CreateCurriculumResponse() {
        }
        
        public CreateCurriculumResponse(bool CreateCurriculumResult, eSAR.CurriculumServiceRef.Curriculum curriculum, string message) {
            this.CreateCurriculumResult = CreateCurriculumResult;
            this.curriculum = curriculum;
            this.message = message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICurriculumServiceChannel : eSAR.CurriculumServiceRef.ICurriculumService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CurriculumServiceClient : System.ServiceModel.ClientBase<eSAR.CurriculumServiceRef.ICurriculumService>, eSAR.CurriculumServiceRef.ICurriculumService {
        
        public CurriculumServiceClient() {
        }
        
        public CurriculumServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CurriculumServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurriculumServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurriculumServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public eSAR.CurriculumServiceRef.GradeLevel[] GetAllGradeLevels() {
            return base.Channel.GetAllGradeLevels();
        }
        
        public System.Threading.Tasks.Task<eSAR.CurriculumServiceRef.GradeLevel[]> GetAllGradeLevelsAsync() {
            return base.Channel.GetAllGradeLevelsAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSAR.CurriculumServiceRef.UpdateCurriculumResponse eSAR.CurriculumServiceRef.ICurriculumService.UpdateCurriculum(eSAR.CurriculumServiceRef.UpdateCurriculumRequest request) {
            return base.Channel.UpdateCurriculum(request);
        }
        
        public bool UpdateCurriculum(ref eSAR.CurriculumServiceRef.Curriculum curriculum, ref string message) {
            eSAR.CurriculumServiceRef.UpdateCurriculumRequest inValue = new eSAR.CurriculumServiceRef.UpdateCurriculumRequest();
            inValue.curriculum = curriculum;
            inValue.message = message;
            eSAR.CurriculumServiceRef.UpdateCurriculumResponse retVal = ((eSAR.CurriculumServiceRef.ICurriculumService)(this)).UpdateCurriculum(inValue);
            curriculum = retVal.curriculum;
            message = retVal.message;
            return retVal.UpdateCurriculumResult;
        }
        
        public System.Threading.Tasks.Task<eSAR.CurriculumServiceRef.UpdateCurriculumResponse> UpdateCurriculumAsync(eSAR.CurriculumServiceRef.UpdateCurriculumRequest request) {
            return base.Channel.UpdateCurriculumAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSAR.CurriculumServiceRef.CreateCurriculumResponse eSAR.CurriculumServiceRef.ICurriculumService.CreateCurriculum(eSAR.CurriculumServiceRef.CreateCurriculumRequest request) {
            return base.Channel.CreateCurriculum(request);
        }
        
        public bool CreateCurriculum(ref eSAR.CurriculumServiceRef.Curriculum curriculum, ref string message) {
            eSAR.CurriculumServiceRef.CreateCurriculumRequest inValue = new eSAR.CurriculumServiceRef.CreateCurriculumRequest();
            inValue.curriculum = curriculum;
            inValue.message = message;
            eSAR.CurriculumServiceRef.CreateCurriculumResponse retVal = ((eSAR.CurriculumServiceRef.ICurriculumService)(this)).CreateCurriculum(inValue);
            curriculum = retVal.curriculum;
            message = retVal.message;
            return retVal.CreateCurriculumResult;
        }
        
        public System.Threading.Tasks.Task<eSAR.CurriculumServiceRef.CreateCurriculumResponse> CreateCurriculumAsync(eSAR.CurriculumServiceRef.CreateCurriculumRequest request) {
            return base.Channel.CreateCurriculumAsync(request);
        }
        
        public eSAR.CurriculumServiceRef.Curriculum[] GetAllCurriculums() {
            return base.Channel.GetAllCurriculums();
        }
        
        public System.Threading.Tasks.Task<eSAR.CurriculumServiceRef.Curriculum[]> GetAllCurriculumsAsync() {
            return base.Channel.GetAllCurriculumsAsync();
        }
        
        public eSAR.CurriculumServiceRef.CurriculumSubject[] GetCurriculumSubjects(string curriculumCode) {
            return base.Channel.GetCurriculumSubjects(curriculumCode);
        }
        
        public System.Threading.Tasks.Task<eSAR.CurriculumServiceRef.CurriculumSubject[]> GetCurriculumSubjectsAsync(string curriculumCode) {
            return base.Channel.GetCurriculumSubjectsAsync(curriculumCode);
        }
        
        public eSAR.CurriculumServiceRef.CurriculumSubject[] GetAllSubjectDetails() {
            return base.Channel.GetAllSubjectDetails();
        }
        
        public System.Threading.Tasks.Task<eSAR.CurriculumServiceRef.CurriculumSubject[]> GetAllSubjectDetailsAsync() {
            return base.Channel.GetAllSubjectDetailsAsync();
        }
        
        public eSAR.CurriculumServiceRef.CurriculumSubject[] GetAllSubjectsOfGradeLevel(string gradeLevel) {
            return base.Channel.GetAllSubjectsOfGradeLevel(gradeLevel);
        }
        
        public System.Threading.Tasks.Task<eSAR.CurriculumServiceRef.CurriculumSubject[]> GetAllSubjectsOfGradeLevelAsync(string gradeLevel) {
            return base.Channel.GetAllSubjectsOfGradeLevelAsync(gradeLevel);
        }
    }
}
