//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSAR.StudentServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Student", Namespace="http://schemas.datacontract.org/2004/07/eSARService")]
    [System.SerializableAttribute()]
    public partial class Student : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> AverageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> BirthCertificateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> CardField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateAdmittedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DismissedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> FathersAverageYearlyIncomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FathersEducationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FathersNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FathersOccupationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> GoodMoralField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradeLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool GraduateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> GuardiansAverageYearlyIncomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuardiansNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuardiansOccupationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomeAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomeBarangayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomeProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HomeTownCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastSYAttendedDCFIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> MadrasahEnrolledField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> MothersAverageYearlyIncomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MothersEducationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MothersMaidenNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MothersOccupationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string POBAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string POBBarangayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string POBProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string POBTownCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReligionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScholarshipCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eSAR.StudentServiceRef.Scholarship ScholarshipsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SchoolLastAttendedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eSAR.StudentServiceRef.Sibling[] SiblingsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Average {
            get {
                return this.AverageField;
            }
            set {
                if ((this.AverageField.Equals(value) != true)) {
                    this.AverageField = value;
                    this.RaisePropertyChanged("Average");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> BirthCertificate {
            get {
                return this.BirthCertificateField;
            }
            set {
                if ((this.BirthCertificateField.Equals(value) != true)) {
                    this.BirthCertificateField = value;
                    this.RaisePropertyChanged("BirthCertificate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Card {
            get {
                return this.CardField;
            }
            set {
                if ((this.CardField.Equals(value) != true)) {
                    this.CardField = value;
                    this.RaisePropertyChanged("Card");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((this.DOBField.Equals(value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateAdmitted {
            get {
                return this.DateAdmittedField;
            }
            set {
                if ((this.DateAdmittedField.Equals(value) != true)) {
                    this.DateAdmittedField = value;
                    this.RaisePropertyChanged("DateAdmitted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Dismissed {
            get {
                return this.DismissedField;
            }
            set {
                if ((this.DismissedField.Equals(value) != true)) {
                    this.DismissedField = value;
                    this.RaisePropertyChanged("Dismissed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> FathersAverageYearlyIncome {
            get {
                return this.FathersAverageYearlyIncomeField;
            }
            set {
                if ((this.FathersAverageYearlyIncomeField.Equals(value) != true)) {
                    this.FathersAverageYearlyIncomeField = value;
                    this.RaisePropertyChanged("FathersAverageYearlyIncome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FathersEducation {
            get {
                return this.FathersEducationField;
            }
            set {
                if ((object.ReferenceEquals(this.FathersEducationField, value) != true)) {
                    this.FathersEducationField = value;
                    this.RaisePropertyChanged("FathersEducation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FathersName {
            get {
                return this.FathersNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FathersNameField, value) != true)) {
                    this.FathersNameField = value;
                    this.RaisePropertyChanged("FathersName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FathersOccupation {
            get {
                return this.FathersOccupationField;
            }
            set {
                if ((object.ReferenceEquals(this.FathersOccupationField, value) != true)) {
                    this.FathersOccupationField = value;
                    this.RaisePropertyChanged("FathersOccupation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> GoodMoral {
            get {
                return this.GoodMoralField;
            }
            set {
                if ((this.GoodMoralField.Equals(value) != true)) {
                    this.GoodMoralField = value;
                    this.RaisePropertyChanged("GoodMoral");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GradeLevel {
            get {
                return this.GradeLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.GradeLevelField, value) != true)) {
                    this.GradeLevelField = value;
                    this.RaisePropertyChanged("GradeLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Graduate {
            get {
                return this.GraduateField;
            }
            set {
                if ((this.GraduateField.Equals(value) != true)) {
                    this.GraduateField = value;
                    this.RaisePropertyChanged("Graduate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> GuardiansAverageYearlyIncome {
            get {
                return this.GuardiansAverageYearlyIncomeField;
            }
            set {
                if ((this.GuardiansAverageYearlyIncomeField.Equals(value) != true)) {
                    this.GuardiansAverageYearlyIncomeField = value;
                    this.RaisePropertyChanged("GuardiansAverageYearlyIncome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GuardiansName {
            get {
                return this.GuardiansNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GuardiansNameField, value) != true)) {
                    this.GuardiansNameField = value;
                    this.RaisePropertyChanged("GuardiansName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GuardiansOccupation {
            get {
                return this.GuardiansOccupationField;
            }
            set {
                if ((object.ReferenceEquals(this.GuardiansOccupationField, value) != true)) {
                    this.GuardiansOccupationField = value;
                    this.RaisePropertyChanged("GuardiansOccupation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomeAddress {
            get {
                return this.HomeAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeAddressField, value) != true)) {
                    this.HomeAddressField = value;
                    this.RaisePropertyChanged("HomeAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomeBarangay {
            get {
                return this.HomeBarangayField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeBarangayField, value) != true)) {
                    this.HomeBarangayField = value;
                    this.RaisePropertyChanged("HomeBarangay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomeProvince {
            get {
                return this.HomeProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeProvinceField, value) != true)) {
                    this.HomeProvinceField = value;
                    this.RaisePropertyChanged("HomeProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HomeTownCity {
            get {
                return this.HomeTownCityField;
            }
            set {
                if ((object.ReferenceEquals(this.HomeTownCityField, value) != true)) {
                    this.HomeTownCityField = value;
                    this.RaisePropertyChanged("HomeTownCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastSYAttendedDCFI {
            get {
                return this.LastSYAttendedDCFIField;
            }
            set {
                if ((object.ReferenceEquals(this.LastSYAttendedDCFIField, value) != true)) {
                    this.LastSYAttendedDCFIField = value;
                    this.RaisePropertyChanged("LastSYAttendedDCFI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> MadrasahEnrolled {
            get {
                return this.MadrasahEnrolledField;
            }
            set {
                if ((this.MadrasahEnrolledField.Equals(value) != true)) {
                    this.MadrasahEnrolledField = value;
                    this.RaisePropertyChanged("MadrasahEnrolled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> MothersAverageYearlyIncome {
            get {
                return this.MothersAverageYearlyIncomeField;
            }
            set {
                if ((this.MothersAverageYearlyIncomeField.Equals(value) != true)) {
                    this.MothersAverageYearlyIncomeField = value;
                    this.RaisePropertyChanged("MothersAverageYearlyIncome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MothersEducation {
            get {
                return this.MothersEducationField;
            }
            set {
                if ((object.ReferenceEquals(this.MothersEducationField, value) != true)) {
                    this.MothersEducationField = value;
                    this.RaisePropertyChanged("MothersEducation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MothersMaidenName {
            get {
                return this.MothersMaidenNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MothersMaidenNameField, value) != true)) {
                    this.MothersMaidenNameField = value;
                    this.RaisePropertyChanged("MothersMaidenName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MothersOccupation {
            get {
                return this.MothersOccupationField;
            }
            set {
                if ((object.ReferenceEquals(this.MothersOccupationField, value) != true)) {
                    this.MothersOccupationField = value;
                    this.RaisePropertyChanged("MothersOccupation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string POBAddress {
            get {
                return this.POBAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.POBAddressField, value) != true)) {
                    this.POBAddressField = value;
                    this.RaisePropertyChanged("POBAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string POBBarangay {
            get {
                return this.POBBarangayField;
            }
            set {
                if ((object.ReferenceEquals(this.POBBarangayField, value) != true)) {
                    this.POBBarangayField = value;
                    this.RaisePropertyChanged("POBBarangay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string POBProvince {
            get {
                return this.POBProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.POBProvinceField, value) != true)) {
                    this.POBProvinceField = value;
                    this.RaisePropertyChanged("POBProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string POBTownCity {
            get {
                return this.POBTownCityField;
            }
            set {
                if ((object.ReferenceEquals(this.POBTownCityField, value) != true)) {
                    this.POBTownCityField = value;
                    this.RaisePropertyChanged("POBTownCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Religion {
            get {
                return this.ReligionField;
            }
            set {
                if ((object.ReferenceEquals(this.ReligionField, value) != true)) {
                    this.ReligionField = value;
                    this.RaisePropertyChanged("Religion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScholarshipCode {
            get {
                return this.ScholarshipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ScholarshipCodeField, value) != true)) {
                    this.ScholarshipCodeField = value;
                    this.RaisePropertyChanged("ScholarshipCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eSAR.StudentServiceRef.Scholarship Scholarships {
            get {
                return this.ScholarshipsField;
            }
            set {
                if ((object.ReferenceEquals(this.ScholarshipsField, value) != true)) {
                    this.ScholarshipsField = value;
                    this.RaisePropertyChanged("Scholarships");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SchoolLastAttended {
            get {
                return this.SchoolLastAttendedField;
            }
            set {
                if ((object.ReferenceEquals(this.SchoolLastAttendedField, value) != true)) {
                    this.SchoolLastAttendedField = value;
                    this.RaisePropertyChanged("SchoolLastAttended");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eSAR.StudentServiceRef.Sibling[] Siblings {
            get {
                return this.SiblingsField;
            }
            set {
                if ((object.ReferenceEquals(this.SiblingsField, value) != true)) {
                    this.SiblingsField = value;
                    this.RaisePropertyChanged("Siblings");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentIdField, value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Scholarship", Namespace="http://schemas.datacontract.org/2004/07/eSARService")]
    [System.SerializableAttribute()]
    public partial class Scholarship : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeactivatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrivilegeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScholarshipCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Condition {
            get {
                return this.ConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.ConditionField, value) != true)) {
                    this.ConditionField = value;
                    this.RaisePropertyChanged("Condition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deactivated {
            get {
                return this.DeactivatedField;
            }
            set {
                if ((this.DeactivatedField.Equals(value) != true)) {
                    this.DeactivatedField = value;
                    this.RaisePropertyChanged("Deactivated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Privilege {
            get {
                return this.PrivilegeField;
            }
            set {
                if ((object.ReferenceEquals(this.PrivilegeField, value) != true)) {
                    this.PrivilegeField = value;
                    this.RaisePropertyChanged("Privilege");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScholarshipCode {
            get {
                return this.ScholarshipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ScholarshipCodeField, value) != true)) {
                    this.ScholarshipCodeField = value;
                    this.RaisePropertyChanged("ScholarshipCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Sibling", Namespace="http://schemas.datacontract.org/2004/07/eSARService")]
    [System.SerializableAttribute()]
    public partial class Sibling : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SiblingIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SiblingStudentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StudentIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SiblingId {
            get {
                return this.SiblingIdField;
            }
            set {
                if ((this.SiblingIdField.Equals(value) != true)) {
                    this.SiblingIdField = value;
                    this.RaisePropertyChanged("SiblingId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SiblingStudentId {
            get {
                return this.SiblingStudentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.SiblingStudentIdField, value) != true)) {
                    this.SiblingStudentIdField = value;
                    this.RaisePropertyChanged("SiblingStudentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StudentId {
            get {
                return this.StudentIdField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentIdField, value) != true)) {
                    this.StudentIdField = value;
                    this.RaisePropertyChanged("StudentId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentServiceRef.IStudentService")]
    public interface IStudentService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/UpdateStudent", ReplyAction="http://tempuri.org/IStudentService/UpdateStudentResponse")]
        eSAR.StudentServiceRef.UpdateStudentResponse UpdateStudent(eSAR.StudentServiceRef.UpdateStudentRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/UpdateStudent", ReplyAction="http://tempuri.org/IStudentService/UpdateStudentResponse")]
        System.Threading.Tasks.Task<eSAR.StudentServiceRef.UpdateStudentResponse> UpdateStudentAsync(eSAR.StudentServiceRef.UpdateStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/DismissStudent", ReplyAction="http://tempuri.org/IStudentService/DismissStudentResponse")]
        eSAR.StudentServiceRef.DismissStudentResponse DismissStudent(eSAR.StudentServiceRef.DismissStudentRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/DismissStudent", ReplyAction="http://tempuri.org/IStudentService/DismissStudentResponse")]
        System.Threading.Tasks.Task<eSAR.StudentServiceRef.DismissStudentResponse> DismissStudentAsync(eSAR.StudentServiceRef.DismissStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GraduateStudent", ReplyAction="http://tempuri.org/IStudentService/GraduateStudentResponse")]
        eSAR.StudentServiceRef.GraduateStudentResponse GraduateStudent(eSAR.StudentServiceRef.GraduateStudentRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GraduateStudent", ReplyAction="http://tempuri.org/IStudentService/GraduateStudentResponse")]
        System.Threading.Tasks.Task<eSAR.StudentServiceRef.GraduateStudentResponse> GraduateStudentAsync(eSAR.StudentServiceRef.GraduateStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/CreateStudent", ReplyAction="http://tempuri.org/IStudentService/CreateStudentResponse")]
        eSAR.StudentServiceRef.CreateStudentResponse CreateStudent(eSAR.StudentServiceRef.CreateStudentRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/CreateStudent", ReplyAction="http://tempuri.org/IStudentService/CreateStudentResponse")]
        System.Threading.Tasks.Task<eSAR.StudentServiceRef.CreateStudentResponse> CreateStudentAsync(eSAR.StudentServiceRef.CreateStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetAllStudents", ReplyAction="http://tempuri.org/IStudentService/GetAllStudentsResponse")]
        eSAR.StudentServiceRef.Student[] GetAllStudents();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetAllStudents", ReplyAction="http://tempuri.org/IStudentService/GetAllStudentsResponse")]
        System.Threading.Tasks.Task<eSAR.StudentServiceRef.Student[]> GetAllStudentsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudent", ReplyAction="http://tempuri.org/IStudentService/GetStudentResponse")]
        eSAR.StudentServiceRef.GetStudentResponse GetStudent(eSAR.StudentServiceRef.GetStudentRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GetStudent", ReplyAction="http://tempuri.org/IStudentService/GetStudentResponse")]
        System.Threading.Tasks.Task<eSAR.StudentServiceRef.GetStudentResponse> GetStudentAsync(eSAR.StudentServiceRef.GetStudentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GenerateStudentId", ReplyAction="http://tempuri.org/IStudentService/GenerateStudentIdResponse")]
        string GenerateStudentId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IStudentService/GenerateStudentId", ReplyAction="http://tempuri.org/IStudentService/GenerateStudentIdResponse")]
        System.Threading.Tasks.Task<string> GenerateStudentIdAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateStudent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public eSAR.StudentServiceRef.Student student;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public UpdateStudentRequest() {
        }
        
        public UpdateStudentRequest(eSAR.StudentServiceRef.Student student, string message) {
            this.student = student;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateStudentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UpdateStudentResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public eSAR.StudentServiceRef.Student student;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string message;
        
        public UpdateStudentResponse() {
        }
        
        public UpdateStudentResponse(bool UpdateStudentResult, eSAR.StudentServiceRef.Student student, string message) {
            this.UpdateStudentResult = UpdateStudentResult;
            this.student = student;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DismissStudent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DismissStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string studentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public DismissStudentRequest() {
        }
        
        public DismissStudentRequest(string studentID, string message) {
            this.studentID = studentID;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DismissStudentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DismissStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DismissStudentResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public DismissStudentResponse() {
        }
        
        public DismissStudentResponse(bool DismissStudentResult, string message) {
            this.DismissStudentResult = DismissStudentResult;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GraduateStudent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GraduateStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string studentID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public GraduateStudentRequest() {
        }
        
        public GraduateStudentRequest(string studentID, string message) {
            this.studentID = studentID;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GraduateStudentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GraduateStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool GraduateStudentResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public GraduateStudentResponse() {
        }
        
        public GraduateStudentResponse(bool GraduateStudentResult, string message) {
            this.GraduateStudentResult = GraduateStudentResult;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateStudent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public eSAR.StudentServiceRef.Student student;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public CreateStudentRequest() {
        }
        
        public CreateStudentRequest(eSAR.StudentServiceRef.Student student, string message) {
            this.student = student;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateStudentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CreateStudentResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public eSAR.StudentServiceRef.Student student;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string message;
        
        public CreateStudentResponse() {
        }
        
        public CreateStudentResponse(bool CreateStudentResult, eSAR.StudentServiceRef.Student student, string message) {
            this.CreateStudentResult = CreateStudentResult;
            this.student = student;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStudent", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStudentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string studentId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public GetStudentRequest() {
        }
        
        public GetStudentRequest(string studentId, string message) {
            this.studentId = studentId;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetStudentResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetStudentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public eSAR.StudentServiceRef.Student GetStudentResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public GetStudentResponse() {
        }
        
        public GetStudentResponse(eSAR.StudentServiceRef.Student GetStudentResult, string message) {
            this.GetStudentResult = GetStudentResult;
            this.message = message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IStudentServiceChannel : eSAR.StudentServiceRef.IStudentService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StudentServiceClient : System.ServiceModel.ClientBase<eSAR.StudentServiceRef.IStudentService>, eSAR.StudentServiceRef.IStudentService {
        
        public StudentServiceClient() {
        }
        
        public StudentServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StudentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSAR.StudentServiceRef.UpdateStudentResponse eSAR.StudentServiceRef.IStudentService.UpdateStudent(eSAR.StudentServiceRef.UpdateStudentRequest request) {
            return base.Channel.UpdateStudent(request);
        }
        
        public bool UpdateStudent(ref eSAR.StudentServiceRef.Student student, ref string message) {
            eSAR.StudentServiceRef.UpdateStudentRequest inValue = new eSAR.StudentServiceRef.UpdateStudentRequest();
            inValue.student = student;
            inValue.message = message;
            eSAR.StudentServiceRef.UpdateStudentResponse retVal = ((eSAR.StudentServiceRef.IStudentService)(this)).UpdateStudent(inValue);
            student = retVal.student;
            message = retVal.message;
            return retVal.UpdateStudentResult;
        }
        
        public System.Threading.Tasks.Task<eSAR.StudentServiceRef.UpdateStudentResponse> UpdateStudentAsync(eSAR.StudentServiceRef.UpdateStudentRequest request) {
            return base.Channel.UpdateStudentAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSAR.StudentServiceRef.DismissStudentResponse eSAR.StudentServiceRef.IStudentService.DismissStudent(eSAR.StudentServiceRef.DismissStudentRequest request) {
            return base.Channel.DismissStudent(request);
        }
        
        public bool DismissStudent(string studentID, ref string message) {
            eSAR.StudentServiceRef.DismissStudentRequest inValue = new eSAR.StudentServiceRef.DismissStudentRequest();
            inValue.studentID = studentID;
            inValue.message = message;
            eSAR.StudentServiceRef.DismissStudentResponse retVal = ((eSAR.StudentServiceRef.IStudentService)(this)).DismissStudent(inValue);
            message = retVal.message;
            return retVal.DismissStudentResult;
        }
        
        public System.Threading.Tasks.Task<eSAR.StudentServiceRef.DismissStudentResponse> DismissStudentAsync(eSAR.StudentServiceRef.DismissStudentRequest request) {
            return base.Channel.DismissStudentAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSAR.StudentServiceRef.GraduateStudentResponse eSAR.StudentServiceRef.IStudentService.GraduateStudent(eSAR.StudentServiceRef.GraduateStudentRequest request) {
            return base.Channel.GraduateStudent(request);
        }
        
        public bool GraduateStudent(string studentID, ref string message) {
            eSAR.StudentServiceRef.GraduateStudentRequest inValue = new eSAR.StudentServiceRef.GraduateStudentRequest();
            inValue.studentID = studentID;
            inValue.message = message;
            eSAR.StudentServiceRef.GraduateStudentResponse retVal = ((eSAR.StudentServiceRef.IStudentService)(this)).GraduateStudent(inValue);
            message = retVal.message;
            return retVal.GraduateStudentResult;
        }
        
        public System.Threading.Tasks.Task<eSAR.StudentServiceRef.GraduateStudentResponse> GraduateStudentAsync(eSAR.StudentServiceRef.GraduateStudentRequest request) {
            return base.Channel.GraduateStudentAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSAR.StudentServiceRef.CreateStudentResponse eSAR.StudentServiceRef.IStudentService.CreateStudent(eSAR.StudentServiceRef.CreateStudentRequest request) {
            return base.Channel.CreateStudent(request);
        }
        
        public bool CreateStudent(ref eSAR.StudentServiceRef.Student student, ref string message) {
            eSAR.StudentServiceRef.CreateStudentRequest inValue = new eSAR.StudentServiceRef.CreateStudentRequest();
            inValue.student = student;
            inValue.message = message;
            eSAR.StudentServiceRef.CreateStudentResponse retVal = ((eSAR.StudentServiceRef.IStudentService)(this)).CreateStudent(inValue);
            student = retVal.student;
            message = retVal.message;
            return retVal.CreateStudentResult;
        }
        
        public System.Threading.Tasks.Task<eSAR.StudentServiceRef.CreateStudentResponse> CreateStudentAsync(eSAR.StudentServiceRef.CreateStudentRequest request) {
            return base.Channel.CreateStudentAsync(request);
        }
        
        public eSAR.StudentServiceRef.Student[] GetAllStudents() {
            return base.Channel.GetAllStudents();
        }
        
        public System.Threading.Tasks.Task<eSAR.StudentServiceRef.Student[]> GetAllStudentsAsync() {
            return base.Channel.GetAllStudentsAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSAR.StudentServiceRef.GetStudentResponse eSAR.StudentServiceRef.IStudentService.GetStudent(eSAR.StudentServiceRef.GetStudentRequest request) {
            return base.Channel.GetStudent(request);
        }
        
        public eSAR.StudentServiceRef.Student GetStudent(string studentId, ref string message) {
            eSAR.StudentServiceRef.GetStudentRequest inValue = new eSAR.StudentServiceRef.GetStudentRequest();
            inValue.studentId = studentId;
            inValue.message = message;
            eSAR.StudentServiceRef.GetStudentResponse retVal = ((eSAR.StudentServiceRef.IStudentService)(this)).GetStudent(inValue);
            message = retVal.message;
            return retVal.GetStudentResult;
        }
        
        public System.Threading.Tasks.Task<eSAR.StudentServiceRef.GetStudentResponse> GetStudentAsync(eSAR.StudentServiceRef.GetStudentRequest request) {
            return base.Channel.GetStudentAsync(request);
        }
        
        public string GenerateStudentId() {
            return base.Channel.GenerateStudentId();
        }
        
        public System.Threading.Tasks.Task<string> GenerateStudentIdAsync() {
            return base.Channel.GenerateStudentIdAsync();
        }
    }
}
