//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSAR.StudentFeeServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fee", Namespace="http://schemas.datacontract.org/2004/07/eSARService")]
    [System.SerializableAttribute()]
    public partial class Fee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeactivatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FeeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FeeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradeLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SYImplementedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateSet {
            get {
                return this.DateSetField;
            }
            set {
                if ((this.DateSetField.Equals(value) != true)) {
                    this.DateSetField = value;
                    this.RaisePropertyChanged("DateSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deactivated {
            get {
                return this.DeactivatedField;
            }
            set {
                if ((this.DeactivatedField.Equals(value) != true)) {
                    this.DeactivatedField = value;
                    this.RaisePropertyChanged("Deactivated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FeeCode {
            get {
                return this.FeeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FeeCodeField, value) != true)) {
                    this.FeeCodeField = value;
                    this.RaisePropertyChanged("FeeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FeeDescription {
            get {
                return this.FeeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.FeeDescriptionField, value) != true)) {
                    this.FeeDescriptionField = value;
                    this.RaisePropertyChanged("FeeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GradeLevel {
            get {
                return this.GradeLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.GradeLevelField, value) != true)) {
                    this.GradeLevelField = value;
                    this.RaisePropertyChanged("GradeLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SYImplemented {
            get {
                return this.SYImplementedField;
            }
            set {
                if ((object.ReferenceEquals(this.SYImplementedField, value) != true)) {
                    this.SYImplementedField = value;
                    this.RaisePropertyChanged("SYImplemented");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="StudentFeeServiceRef.IFeeService")]
    public interface IFeeService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeeService/UpdateFee", ReplyAction="http://tempuri.org/IFeeService/UpdateFeeResponse")]
        eSAR.StudentFeeServiceRef.UpdateFeeResponse UpdateFee(eSAR.StudentFeeServiceRef.UpdateFeeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeeService/UpdateFee", ReplyAction="http://tempuri.org/IFeeService/UpdateFeeResponse")]
        System.Threading.Tasks.Task<eSAR.StudentFeeServiceRef.UpdateFeeResponse> UpdateFeeAsync(eSAR.StudentFeeServiceRef.UpdateFeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeeService/CreateFee", ReplyAction="http://tempuri.org/IFeeService/CreateFeeResponse")]
        eSAR.StudentFeeServiceRef.CreateFeeResponse CreateFee(eSAR.StudentFeeServiceRef.CreateFeeRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeeService/CreateFee", ReplyAction="http://tempuri.org/IFeeService/CreateFeeResponse")]
        System.Threading.Tasks.Task<eSAR.StudentFeeServiceRef.CreateFeeResponse> CreateFeeAsync(eSAR.StudentFeeServiceRef.CreateFeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeeService/GetAllFees", ReplyAction="http://tempuri.org/IFeeService/GetAllFeesResponse")]
        eSAR.StudentFeeServiceRef.Fee[] GetAllFees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeeService/GetAllFees", ReplyAction="http://tempuri.org/IFeeService/GetAllFeesResponse")]
        System.Threading.Tasks.Task<eSAR.StudentFeeServiceRef.Fee[]> GetAllFeesAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateFee", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateFeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public eSAR.StudentFeeServiceRef.Fee fee;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public UpdateFeeRequest() {
        }
        
        public UpdateFeeRequest(eSAR.StudentFeeServiceRef.Fee fee, string message) {
            this.fee = fee;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateFeeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateFeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UpdateFeeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public eSAR.StudentFeeServiceRef.Fee fee;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string message;
        
        public UpdateFeeResponse() {
        }
        
        public UpdateFeeResponse(bool UpdateFeeResult, eSAR.StudentFeeServiceRef.Fee fee, string message) {
            this.UpdateFeeResult = UpdateFeeResult;
            this.fee = fee;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateFee", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateFeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public eSAR.StudentFeeServiceRef.Fee fee;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public CreateFeeRequest() {
        }
        
        public CreateFeeRequest(eSAR.StudentFeeServiceRef.Fee fee, string message) {
            this.fee = fee;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateFeeResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateFeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CreateFeeResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public eSAR.StudentFeeServiceRef.Fee fee;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string message;
        
        public CreateFeeResponse() {
        }
        
        public CreateFeeResponse(bool CreateFeeResult, eSAR.StudentFeeServiceRef.Fee fee, string message) {
            this.CreateFeeResult = CreateFeeResult;
            this.fee = fee;
            this.message = message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFeeServiceChannel : eSAR.StudentFeeServiceRef.IFeeService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FeeServiceClient : System.ServiceModel.ClientBase<eSAR.StudentFeeServiceRef.IFeeService>, eSAR.StudentFeeServiceRef.IFeeService {
        
        public FeeServiceClient() {
        }
        
        public FeeServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FeeServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeeServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FeeServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSAR.StudentFeeServiceRef.UpdateFeeResponse eSAR.StudentFeeServiceRef.IFeeService.UpdateFee(eSAR.StudentFeeServiceRef.UpdateFeeRequest request) {
            return base.Channel.UpdateFee(request);
        }
        
        public bool UpdateFee(ref eSAR.StudentFeeServiceRef.Fee fee, ref string message) {
            eSAR.StudentFeeServiceRef.UpdateFeeRequest inValue = new eSAR.StudentFeeServiceRef.UpdateFeeRequest();
            inValue.fee = fee;
            inValue.message = message;
            eSAR.StudentFeeServiceRef.UpdateFeeResponse retVal = ((eSAR.StudentFeeServiceRef.IFeeService)(this)).UpdateFee(inValue);
            fee = retVal.fee;
            message = retVal.message;
            return retVal.UpdateFeeResult;
        }
        
        public System.Threading.Tasks.Task<eSAR.StudentFeeServiceRef.UpdateFeeResponse> UpdateFeeAsync(eSAR.StudentFeeServiceRef.UpdateFeeRequest request) {
            return base.Channel.UpdateFeeAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSAR.StudentFeeServiceRef.CreateFeeResponse eSAR.StudentFeeServiceRef.IFeeService.CreateFee(eSAR.StudentFeeServiceRef.CreateFeeRequest request) {
            return base.Channel.CreateFee(request);
        }
        
        public bool CreateFee(ref eSAR.StudentFeeServiceRef.Fee fee, ref string message) {
            eSAR.StudentFeeServiceRef.CreateFeeRequest inValue = new eSAR.StudentFeeServiceRef.CreateFeeRequest();
            inValue.fee = fee;
            inValue.message = message;
            eSAR.StudentFeeServiceRef.CreateFeeResponse retVal = ((eSAR.StudentFeeServiceRef.IFeeService)(this)).CreateFee(inValue);
            fee = retVal.fee;
            message = retVal.message;
            return retVal.CreateFeeResult;
        }
        
        public System.Threading.Tasks.Task<eSAR.StudentFeeServiceRef.CreateFeeResponse> CreateFeeAsync(eSAR.StudentFeeServiceRef.CreateFeeRequest request) {
            return base.Channel.CreateFeeAsync(request);
        }
        
        public eSAR.StudentFeeServiceRef.Fee[] GetAllFees() {
            return base.Channel.GetAllFees();
        }
        
        public System.Threading.Tasks.Task<eSAR.StudentFeeServiceRef.Fee[]> GetAllFeesAsync() {
            return base.Channel.GetAllFeesAsync();
        }
    }
}
