//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSAR.TimeslotServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Timeslot", Namespace="http://schemas.datacontract.org/2004/07/eSARService")]
    [System.SerializableAttribute()]
    public partial class Timeslot : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DaysField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeactivatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeSlotCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TimeStartField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Days {
            get {
                return this.DaysField;
            }
            set {
                if ((object.ReferenceEquals(this.DaysField, value) != true)) {
                    this.DaysField = value;
                    this.RaisePropertyChanged("Days");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deactivated {
            get {
                return this.DeactivatedField;
            }
            set {
                if ((this.DeactivatedField.Equals(value) != true)) {
                    this.DeactivatedField = value;
                    this.RaisePropertyChanged("Deactivated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeEnd {
            get {
                return this.TimeEndField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeEndField, value) != true)) {
                    this.TimeEndField = value;
                    this.RaisePropertyChanged("TimeEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeSlotCode {
            get {
                return this.TimeSlotCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeSlotCodeField, value) != true)) {
                    this.TimeSlotCodeField = value;
                    this.RaisePropertyChanged("TimeSlotCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TimeStart {
            get {
                return this.TimeStartField;
            }
            set {
                if ((object.ReferenceEquals(this.TimeStartField, value) != true)) {
                    this.TimeStartField = value;
                    this.RaisePropertyChanged("TimeStart");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TimeslotServiceRef.ITimeslotService")]
    public interface ITimeslotService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeslotService/GetTimeslot", ReplyAction="http://tempuri.org/ITimeslotService/GetTimeslotResponse")]
        eSAR.TimeslotServiceRef.Timeslot GetTimeslot(string timeslotCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeslotService/GetTimeslot", ReplyAction="http://tempuri.org/ITimeslotService/GetTimeslotResponse")]
        System.Threading.Tasks.Task<eSAR.TimeslotServiceRef.Timeslot> GetTimeslotAsync(string timeslotCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeslotService/CreateTimeslot", ReplyAction="http://tempuri.org/ITimeslotService/CreateTimeslotResponse")]
        eSAR.TimeslotServiceRef.CreateTimeslotResponse CreateTimeslot(eSAR.TimeslotServiceRef.CreateTimeslotRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeslotService/CreateTimeslot", ReplyAction="http://tempuri.org/ITimeslotService/CreateTimeslotResponse")]
        System.Threading.Tasks.Task<eSAR.TimeslotServiceRef.CreateTimeslotResponse> CreateTimeslotAsync(eSAR.TimeslotServiceRef.CreateTimeslotRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeslotService/UpdateTimeslot", ReplyAction="http://tempuri.org/ITimeslotService/UpdateTimeslotResponse")]
        eSAR.TimeslotServiceRef.UpdateTimeslotResponse UpdateTimeslot(eSAR.TimeslotServiceRef.UpdateTimeslotRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeslotService/UpdateTimeslot", ReplyAction="http://tempuri.org/ITimeslotService/UpdateTimeslotResponse")]
        System.Threading.Tasks.Task<eSAR.TimeslotServiceRef.UpdateTimeslotResponse> UpdateTimeslotAsync(eSAR.TimeslotServiceRef.UpdateTimeslotRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeslotService/GetAllTimeslots", ReplyAction="http://tempuri.org/ITimeslotService/GetAllTimeslotsResponse")]
        eSAR.TimeslotServiceRef.Timeslot[] GetAllTimeslots();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeslotService/GetAllTimeslots", ReplyAction="http://tempuri.org/ITimeslotService/GetAllTimeslotsResponse")]
        System.Threading.Tasks.Task<eSAR.TimeslotServiceRef.Timeslot[]> GetAllTimeslotsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeslotService/DeactivateTimeslot", ReplyAction="http://tempuri.org/ITimeslotService/DeactivateTimeslotResponse")]
        eSAR.TimeslotServiceRef.DeactivateTimeslotResponse DeactivateTimeslot(eSAR.TimeslotServiceRef.DeactivateTimeslotRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeslotService/DeactivateTimeslot", ReplyAction="http://tempuri.org/ITimeslotService/DeactivateTimeslotResponse")]
        System.Threading.Tasks.Task<eSAR.TimeslotServiceRef.DeactivateTimeslotResponse> DeactivateTimeslotAsync(eSAR.TimeslotServiceRef.DeactivateTimeslotRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeslotService/ActivateTimeslot", ReplyAction="http://tempuri.org/ITimeslotService/ActivateTimeslotResponse")]
        eSAR.TimeslotServiceRef.ActivateTimeslotResponse ActivateTimeslot(eSAR.TimeslotServiceRef.ActivateTimeslotRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeslotService/ActivateTimeslot", ReplyAction="http://tempuri.org/ITimeslotService/ActivateTimeslotResponse")]
        System.Threading.Tasks.Task<eSAR.TimeslotServiceRef.ActivateTimeslotResponse> ActivateTimeslotAsync(eSAR.TimeslotServiceRef.ActivateTimeslotRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeslotService/DeleteTimeslot", ReplyAction="http://tempuri.org/ITimeslotService/DeleteTimeslotResponse")]
        eSAR.TimeslotServiceRef.DeleteTimeslotResponse DeleteTimeslot(eSAR.TimeslotServiceRef.DeleteTimeslotRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITimeslotService/DeleteTimeslot", ReplyAction="http://tempuri.org/ITimeslotService/DeleteTimeslotResponse")]
        System.Threading.Tasks.Task<eSAR.TimeslotServiceRef.DeleteTimeslotResponse> DeleteTimeslotAsync(eSAR.TimeslotServiceRef.DeleteTimeslotRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateTimeslot", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateTimeslotRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public eSAR.TimeslotServiceRef.Timeslot timeslot;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public CreateTimeslotRequest() {
        }
        
        public CreateTimeslotRequest(eSAR.TimeslotServiceRef.Timeslot timeslot, string message) {
            this.timeslot = timeslot;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateTimeslotResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateTimeslotResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CreateTimeslotResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public eSAR.TimeslotServiceRef.Timeslot timeslot;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string message;
        
        public CreateTimeslotResponse() {
        }
        
        public CreateTimeslotResponse(bool CreateTimeslotResult, eSAR.TimeslotServiceRef.Timeslot timeslot, string message) {
            this.CreateTimeslotResult = CreateTimeslotResult;
            this.timeslot = timeslot;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateTimeslot", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateTimeslotRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public eSAR.TimeslotServiceRef.Timeslot timeslot;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public UpdateTimeslotRequest() {
        }
        
        public UpdateTimeslotRequest(eSAR.TimeslotServiceRef.Timeslot timeslot, string message) {
            this.timeslot = timeslot;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateTimeslotResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateTimeslotResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UpdateTimeslotResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public eSAR.TimeslotServiceRef.Timeslot timeslot;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string message;
        
        public UpdateTimeslotResponse() {
        }
        
        public UpdateTimeslotResponse(bool UpdateTimeslotResult, eSAR.TimeslotServiceRef.Timeslot timeslot, string message) {
            this.UpdateTimeslotResult = UpdateTimeslotResult;
            this.timeslot = timeslot;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeactivateTimeslot", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeactivateTimeslotRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string timeslotCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public DeactivateTimeslotRequest() {
        }
        
        public DeactivateTimeslotRequest(string timeslotCode, string message) {
            this.timeslotCode = timeslotCode;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeactivateTimeslotResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeactivateTimeslotResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DeactivateTimeslotResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public DeactivateTimeslotResponse() {
        }
        
        public DeactivateTimeslotResponse(bool DeactivateTimeslotResult, string message) {
            this.DeactivateTimeslotResult = DeactivateTimeslotResult;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActivateTimeslot", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ActivateTimeslotRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string timeslotCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public ActivateTimeslotRequest() {
        }
        
        public ActivateTimeslotRequest(string timeslotCode, string message) {
            this.timeslotCode = timeslotCode;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ActivateTimeslotResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ActivateTimeslotResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool ActivateTimeslotResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public ActivateTimeslotResponse() {
        }
        
        public ActivateTimeslotResponse(bool ActivateTimeslotResult, string message) {
            this.ActivateTimeslotResult = ActivateTimeslotResult;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteTimeslot", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteTimeslotRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string timeslotCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public DeleteTimeslotRequest() {
        }
        
        public DeleteTimeslotRequest(string timeslotCode, string message) {
            this.timeslotCode = timeslotCode;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeleteTimeslotResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeleteTimeslotResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DeleteTimeslotResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public DeleteTimeslotResponse() {
        }
        
        public DeleteTimeslotResponse(bool DeleteTimeslotResult, string message) {
            this.DeleteTimeslotResult = DeleteTimeslotResult;
            this.message = message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITimeslotServiceChannel : eSAR.TimeslotServiceRef.ITimeslotService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TimeslotServiceClient : System.ServiceModel.ClientBase<eSAR.TimeslotServiceRef.ITimeslotService>, eSAR.TimeslotServiceRef.ITimeslotService {
        
        public TimeslotServiceClient() {
        }
        
        public TimeslotServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TimeslotServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeslotServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TimeslotServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public eSAR.TimeslotServiceRef.Timeslot GetTimeslot(string timeslotCode) {
            return base.Channel.GetTimeslot(timeslotCode);
        }
        
        public System.Threading.Tasks.Task<eSAR.TimeslotServiceRef.Timeslot> GetTimeslotAsync(string timeslotCode) {
            return base.Channel.GetTimeslotAsync(timeslotCode);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSAR.TimeslotServiceRef.CreateTimeslotResponse eSAR.TimeslotServiceRef.ITimeslotService.CreateTimeslot(eSAR.TimeslotServiceRef.CreateTimeslotRequest request) {
            return base.Channel.CreateTimeslot(request);
        }
        
        public bool CreateTimeslot(ref eSAR.TimeslotServiceRef.Timeslot timeslot, ref string message) {
            eSAR.TimeslotServiceRef.CreateTimeslotRequest inValue = new eSAR.TimeslotServiceRef.CreateTimeslotRequest();
            inValue.timeslot = timeslot;
            inValue.message = message;
            eSAR.TimeslotServiceRef.CreateTimeslotResponse retVal = ((eSAR.TimeslotServiceRef.ITimeslotService)(this)).CreateTimeslot(inValue);
            timeslot = retVal.timeslot;
            message = retVal.message;
            return retVal.CreateTimeslotResult;
        }
        
        public System.Threading.Tasks.Task<eSAR.TimeslotServiceRef.CreateTimeslotResponse> CreateTimeslotAsync(eSAR.TimeslotServiceRef.CreateTimeslotRequest request) {
            return base.Channel.CreateTimeslotAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSAR.TimeslotServiceRef.UpdateTimeslotResponse eSAR.TimeslotServiceRef.ITimeslotService.UpdateTimeslot(eSAR.TimeslotServiceRef.UpdateTimeslotRequest request) {
            return base.Channel.UpdateTimeslot(request);
        }
        
        public bool UpdateTimeslot(ref eSAR.TimeslotServiceRef.Timeslot timeslot, ref string message) {
            eSAR.TimeslotServiceRef.UpdateTimeslotRequest inValue = new eSAR.TimeslotServiceRef.UpdateTimeslotRequest();
            inValue.timeslot = timeslot;
            inValue.message = message;
            eSAR.TimeslotServiceRef.UpdateTimeslotResponse retVal = ((eSAR.TimeslotServiceRef.ITimeslotService)(this)).UpdateTimeslot(inValue);
            timeslot = retVal.timeslot;
            message = retVal.message;
            return retVal.UpdateTimeslotResult;
        }
        
        public System.Threading.Tasks.Task<eSAR.TimeslotServiceRef.UpdateTimeslotResponse> UpdateTimeslotAsync(eSAR.TimeslotServiceRef.UpdateTimeslotRequest request) {
            return base.Channel.UpdateTimeslotAsync(request);
        }
        
        public eSAR.TimeslotServiceRef.Timeslot[] GetAllTimeslots() {
            return base.Channel.GetAllTimeslots();
        }
        
        public System.Threading.Tasks.Task<eSAR.TimeslotServiceRef.Timeslot[]> GetAllTimeslotsAsync() {
            return base.Channel.GetAllTimeslotsAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSAR.TimeslotServiceRef.DeactivateTimeslotResponse eSAR.TimeslotServiceRef.ITimeslotService.DeactivateTimeslot(eSAR.TimeslotServiceRef.DeactivateTimeslotRequest request) {
            return base.Channel.DeactivateTimeslot(request);
        }
        
        public bool DeactivateTimeslot(string timeslotCode, ref string message) {
            eSAR.TimeslotServiceRef.DeactivateTimeslotRequest inValue = new eSAR.TimeslotServiceRef.DeactivateTimeslotRequest();
            inValue.timeslotCode = timeslotCode;
            inValue.message = message;
            eSAR.TimeslotServiceRef.DeactivateTimeslotResponse retVal = ((eSAR.TimeslotServiceRef.ITimeslotService)(this)).DeactivateTimeslot(inValue);
            message = retVal.message;
            return retVal.DeactivateTimeslotResult;
        }
        
        public System.Threading.Tasks.Task<eSAR.TimeslotServiceRef.DeactivateTimeslotResponse> DeactivateTimeslotAsync(eSAR.TimeslotServiceRef.DeactivateTimeslotRequest request) {
            return base.Channel.DeactivateTimeslotAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSAR.TimeslotServiceRef.ActivateTimeslotResponse eSAR.TimeslotServiceRef.ITimeslotService.ActivateTimeslot(eSAR.TimeslotServiceRef.ActivateTimeslotRequest request) {
            return base.Channel.ActivateTimeslot(request);
        }
        
        public bool ActivateTimeslot(string timeslotCode, ref string message) {
            eSAR.TimeslotServiceRef.ActivateTimeslotRequest inValue = new eSAR.TimeslotServiceRef.ActivateTimeslotRequest();
            inValue.timeslotCode = timeslotCode;
            inValue.message = message;
            eSAR.TimeslotServiceRef.ActivateTimeslotResponse retVal = ((eSAR.TimeslotServiceRef.ITimeslotService)(this)).ActivateTimeslot(inValue);
            message = retVal.message;
            return retVal.ActivateTimeslotResult;
        }
        
        public System.Threading.Tasks.Task<eSAR.TimeslotServiceRef.ActivateTimeslotResponse> ActivateTimeslotAsync(eSAR.TimeslotServiceRef.ActivateTimeslotRequest request) {
            return base.Channel.ActivateTimeslotAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSAR.TimeslotServiceRef.DeleteTimeslotResponse eSAR.TimeslotServiceRef.ITimeslotService.DeleteTimeslot(eSAR.TimeslotServiceRef.DeleteTimeslotRequest request) {
            return base.Channel.DeleteTimeslot(request);
        }
        
        public bool DeleteTimeslot(string timeslotCode, ref string message) {
            eSAR.TimeslotServiceRef.DeleteTimeslotRequest inValue = new eSAR.TimeslotServiceRef.DeleteTimeslotRequest();
            inValue.timeslotCode = timeslotCode;
            inValue.message = message;
            eSAR.TimeslotServiceRef.DeleteTimeslotResponse retVal = ((eSAR.TimeslotServiceRef.ITimeslotService)(this)).DeleteTimeslot(inValue);
            message = retVal.message;
            return retVal.DeleteTimeslotResult;
        }
        
        public System.Threading.Tasks.Task<eSAR.TimeslotServiceRef.DeleteTimeslotResponse> DeleteTimeslotAsync(eSAR.TimeslotServiceRef.DeleteTimeslotRequest request) {
            return base.Channel.DeleteTimeslotAsync(request);
        }
    }
}
