//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSAR.BuildingServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Building", Namespace="http://schemas.datacontract.org/2004/07/eSARService")]
    [System.SerializableAttribute()]
    public partial class Building : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeactivatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eSAR.BuildingServiceRef.Room[] RoomsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingCode {
            get {
                return this.BuildingCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingCodeField, value) != true)) {
                    this.BuildingCodeField = value;
                    this.RaisePropertyChanged("BuildingCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingName {
            get {
                return this.BuildingNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingNameField, value) != true)) {
                    this.BuildingNameField = value;
                    this.RaisePropertyChanged("BuildingName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deactivated {
            get {
                return this.DeactivatedField;
            }
            set {
                if ((this.DeactivatedField.Equals(value) != true)) {
                    this.DeactivatedField = value;
                    this.RaisePropertyChanged("Deactivated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eSAR.BuildingServiceRef.Room[] Rooms {
            get {
                return this.RoomsField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomsField, value) != true)) {
                    this.RoomsField = value;
                    this.RaisePropertyChanged("Rooms");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Room", Namespace="http://schemas.datacontract.org/2004/07/eSARService")]
    [System.SerializableAttribute()]
    public partial class Room : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BuildingCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CapacityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeactivatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoomIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoomNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BuildingCode {
            get {
                return this.BuildingCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BuildingCodeField, value) != true)) {
                    this.BuildingCodeField = value;
                    this.RaisePropertyChanged("BuildingCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Capacity {
            get {
                return this.CapacityField;
            }
            set {
                if ((this.CapacityField.Equals(value) != true)) {
                    this.CapacityField = value;
                    this.RaisePropertyChanged("Capacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deactivated {
            get {
                return this.DeactivatedField;
            }
            set {
                if ((this.DeactivatedField.Equals(value) != true)) {
                    this.DeactivatedField = value;
                    this.RaisePropertyChanged("Deactivated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomCode {
            get {
                return this.RoomCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomCodeField, value) != true)) {
                    this.RoomCodeField = value;
                    this.RaisePropertyChanged("RoomCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoomId {
            get {
                return this.RoomIdField;
            }
            set {
                if ((this.RoomIdField.Equals(value) != true)) {
                    this.RoomIdField = value;
                    this.RaisePropertyChanged("RoomId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoomNumber {
            get {
                return this.RoomNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.RoomNumberField, value) != true)) {
                    this.RoomNumberField = value;
                    this.RaisePropertyChanged("RoomNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BuildingServiceRef.IBuildingService")]
    public interface IBuildingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuildingService/UpdateBuilding", ReplyAction="http://tempuri.org/IBuildingService/UpdateBuildingResponse")]
        eSAR.BuildingServiceRef.UpdateBuildingResponse UpdateBuilding(eSAR.BuildingServiceRef.UpdateBuildingRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuildingService/UpdateBuilding", ReplyAction="http://tempuri.org/IBuildingService/UpdateBuildingResponse")]
        System.Threading.Tasks.Task<eSAR.BuildingServiceRef.UpdateBuildingResponse> UpdateBuildingAsync(eSAR.BuildingServiceRef.UpdateBuildingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuildingService/CreateBuilding", ReplyAction="http://tempuri.org/IBuildingService/CreateBuildingResponse")]
        eSAR.BuildingServiceRef.CreateBuildingResponse CreateBuilding(eSAR.BuildingServiceRef.CreateBuildingRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuildingService/CreateBuilding", ReplyAction="http://tempuri.org/IBuildingService/CreateBuildingResponse")]
        System.Threading.Tasks.Task<eSAR.BuildingServiceRef.CreateBuildingResponse> CreateBuildingAsync(eSAR.BuildingServiceRef.CreateBuildingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuildingService/GetAllBuildings", ReplyAction="http://tempuri.org/IBuildingService/GetAllBuildingsResponse")]
        eSAR.BuildingServiceRef.Building[] GetAllBuildings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuildingService/GetAllBuildings", ReplyAction="http://tempuri.org/IBuildingService/GetAllBuildingsResponse")]
        System.Threading.Tasks.Task<eSAR.BuildingServiceRef.Building[]> GetAllBuildingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuildingService/GetAllRooms", ReplyAction="http://tempuri.org/IBuildingService/GetAllRoomsResponse")]
        eSAR.BuildingServiceRef.Room[] GetAllRooms(string buildingCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBuildingService/GetAllRooms", ReplyAction="http://tempuri.org/IBuildingService/GetAllRoomsResponse")]
        System.Threading.Tasks.Task<eSAR.BuildingServiceRef.Room[]> GetAllRoomsAsync(string buildingCode);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateBuilding", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateBuildingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public eSAR.BuildingServiceRef.Building building;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public UpdateBuildingRequest() {
        }
        
        public UpdateBuildingRequest(eSAR.BuildingServiceRef.Building building, string message) {
            this.building = building;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateBuildingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateBuildingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UpdateBuildingResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public eSAR.BuildingServiceRef.Building building;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string message;
        
        public UpdateBuildingResponse() {
        }
        
        public UpdateBuildingResponse(bool UpdateBuildingResult, eSAR.BuildingServiceRef.Building building, string message) {
            this.UpdateBuildingResult = UpdateBuildingResult;
            this.building = building;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateBuilding", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateBuildingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public eSAR.BuildingServiceRef.Building building;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public CreateBuildingRequest() {
        }
        
        public CreateBuildingRequest(eSAR.BuildingServiceRef.Building building, string message) {
            this.building = building;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateBuildingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateBuildingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CreateBuildingResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public eSAR.BuildingServiceRef.Building building;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string message;
        
        public CreateBuildingResponse() {
        }
        
        public CreateBuildingResponse(bool CreateBuildingResult, eSAR.BuildingServiceRef.Building building, string message) {
            this.CreateBuildingResult = CreateBuildingResult;
            this.building = building;
            this.message = message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBuildingServiceChannel : eSAR.BuildingServiceRef.IBuildingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BuildingServiceClient : System.ServiceModel.ClientBase<eSAR.BuildingServiceRef.IBuildingService>, eSAR.BuildingServiceRef.IBuildingService {
        
        public BuildingServiceClient() {
        }
        
        public BuildingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BuildingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BuildingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BuildingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSAR.BuildingServiceRef.UpdateBuildingResponse eSAR.BuildingServiceRef.IBuildingService.UpdateBuilding(eSAR.BuildingServiceRef.UpdateBuildingRequest request) {
            return base.Channel.UpdateBuilding(request);
        }
        
        public bool UpdateBuilding(ref eSAR.BuildingServiceRef.Building building, ref string message) {
            eSAR.BuildingServiceRef.UpdateBuildingRequest inValue = new eSAR.BuildingServiceRef.UpdateBuildingRequest();
            inValue.building = building;
            inValue.message = message;
            eSAR.BuildingServiceRef.UpdateBuildingResponse retVal = ((eSAR.BuildingServiceRef.IBuildingService)(this)).UpdateBuilding(inValue);
            building = retVal.building;
            message = retVal.message;
            return retVal.UpdateBuildingResult;
        }
        
        public System.Threading.Tasks.Task<eSAR.BuildingServiceRef.UpdateBuildingResponse> UpdateBuildingAsync(eSAR.BuildingServiceRef.UpdateBuildingRequest request) {
            return base.Channel.UpdateBuildingAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSAR.BuildingServiceRef.CreateBuildingResponse eSAR.BuildingServiceRef.IBuildingService.CreateBuilding(eSAR.BuildingServiceRef.CreateBuildingRequest request) {
            return base.Channel.CreateBuilding(request);
        }
        
        public bool CreateBuilding(ref eSAR.BuildingServiceRef.Building building, ref string message) {
            eSAR.BuildingServiceRef.CreateBuildingRequest inValue = new eSAR.BuildingServiceRef.CreateBuildingRequest();
            inValue.building = building;
            inValue.message = message;
            eSAR.BuildingServiceRef.CreateBuildingResponse retVal = ((eSAR.BuildingServiceRef.IBuildingService)(this)).CreateBuilding(inValue);
            building = retVal.building;
            message = retVal.message;
            return retVal.CreateBuildingResult;
        }
        
        public System.Threading.Tasks.Task<eSAR.BuildingServiceRef.CreateBuildingResponse> CreateBuildingAsync(eSAR.BuildingServiceRef.CreateBuildingRequest request) {
            return base.Channel.CreateBuildingAsync(request);
        }
        
        public eSAR.BuildingServiceRef.Building[] GetAllBuildings() {
            return base.Channel.GetAllBuildings();
        }
        
        public System.Threading.Tasks.Task<eSAR.BuildingServiceRef.Building[]> GetAllBuildingsAsync() {
            return base.Channel.GetAllBuildingsAsync();
        }
        
        public eSAR.BuildingServiceRef.Room[] GetAllRooms(string buildingCode) {
            return base.Channel.GetAllRooms(buildingCode);
        }
        
        public System.Threading.Tasks.Task<eSAR.BuildingServiceRef.Room[]> GetAllRoomsAsync(string buildingCode) {
            return base.Channel.GetAllRoomsAsync(buildingCode);
        }
    }
}
