//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSAR.GradeLevelServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GradeLevel", Namespace="http://schemas.datacontract.org/2004/07/eSARService")]
    [System.SerializableAttribute()]
    public partial class GradeLevel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradeLevField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eSAR.GradeLevelServiceRef.Fee[] StudentFeesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eSAR.GradeLevelServiceRef.Trait[] TraitsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GradeLev {
            get {
                return this.GradeLevField;
            }
            set {
                if ((object.ReferenceEquals(this.GradeLevField, value) != true)) {
                    this.GradeLevField = value;
                    this.RaisePropertyChanged("GradeLev");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eSAR.GradeLevelServiceRef.Fee[] StudentFees {
            get {
                return this.StudentFeesField;
            }
            set {
                if ((object.ReferenceEquals(this.StudentFeesField, value) != true)) {
                    this.StudentFeesField = value;
                    this.RaisePropertyChanged("StudentFees");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eSAR.GradeLevelServiceRef.Trait[] Traits {
            get {
                return this.TraitsField;
            }
            set {
                if ((object.ReferenceEquals(this.TraitsField, value) != true)) {
                    this.TraitsField = value;
                    this.RaisePropertyChanged("Traits");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fee", Namespace="http://schemas.datacontract.org/2004/07/eSARService")]
    [System.SerializableAttribute()]
    public partial class Fee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> DateSetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeactivatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FeeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FeeDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradeLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SYImplementedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DateSet {
            get {
                return this.DateSetField;
            }
            set {
                if ((this.DateSetField.Equals(value) != true)) {
                    this.DateSetField = value;
                    this.RaisePropertyChanged("DateSet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deactivated {
            get {
                return this.DeactivatedField;
            }
            set {
                if ((this.DeactivatedField.Equals(value) != true)) {
                    this.DeactivatedField = value;
                    this.RaisePropertyChanged("Deactivated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FeeCode {
            get {
                return this.FeeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FeeCodeField, value) != true)) {
                    this.FeeCodeField = value;
                    this.RaisePropertyChanged("FeeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FeeDescription {
            get {
                return this.FeeDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.FeeDescriptionField, value) != true)) {
                    this.FeeDescriptionField = value;
                    this.RaisePropertyChanged("FeeDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GradeLevel {
            get {
                return this.GradeLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.GradeLevelField, value) != true)) {
                    this.GradeLevelField = value;
                    this.RaisePropertyChanged("GradeLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SYImplemented {
            get {
                return this.SYImplementedField;
            }
            set {
                if ((object.ReferenceEquals(this.SYImplementedField, value) != true)) {
                    this.SYImplementedField = value;
                    this.RaisePropertyChanged("SYImplemented");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Trait", Namespace="http://schemas.datacontract.org/2004/07/eSARService")]
    [System.SerializableAttribute()]
    public partial class Trait : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GradeLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TraitCodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GradeLevel {
            get {
                return this.GradeLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.GradeLevelField, value) != true)) {
                    this.GradeLevelField = value;
                    this.RaisePropertyChanged("GradeLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TraitCode {
            get {
                return this.TraitCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TraitCodeField, value) != true)) {
                    this.TraitCodeField = value;
                    this.RaisePropertyChanged("TraitCode");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="GradeLevelServiceRef.IGradeLevelService")]
    public interface IGradeLevelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGradeLevelService/GetAllGradeLevels", ReplyAction="http://tempuri.org/IGradeLevelService/GetAllGradeLevelsResponse")]
        eSAR.GradeLevelServiceRef.GradeLevel[] GetAllGradeLevels();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGradeLevelService/GetAllGradeLevels", ReplyAction="http://tempuri.org/IGradeLevelService/GetAllGradeLevelsResponse")]
        System.Threading.Tasks.Task<eSAR.GradeLevelServiceRef.GradeLevel[]> GetAllGradeLevelsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGradeLevelServiceChannel : eSAR.GradeLevelServiceRef.IGradeLevelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GradeLevelServiceClient : System.ServiceModel.ClientBase<eSAR.GradeLevelServiceRef.IGradeLevelService>, eSAR.GradeLevelServiceRef.IGradeLevelService {
        
        public GradeLevelServiceClient() {
        }
        
        public GradeLevelServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GradeLevelServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GradeLevelServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GradeLevelServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public eSAR.GradeLevelServiceRef.GradeLevel[] GetAllGradeLevels() {
            return base.Channel.GetAllGradeLevels();
        }
        
        public System.Threading.Tasks.Task<eSAR.GradeLevelServiceRef.GradeLevel[]> GetAllGradeLevelsAsync() {
            return base.Channel.GetAllGradeLevelsAsync();
        }
    }
}
