//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSARDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassList
    {
        public string StudentId { get; set; }
        public string Fullname_lmf { get; set; }
        public string StudentSY { get; set; }
        public Nullable<int> GradeSectionCode { get; set; }
        public string SY { get; set; }
        public int SubjectAssignmentNumber { get; set; }
        public string SubjectCode { get; set; }
        public string RoomCode { get; set; }
        public string TeacherId { get; set; }
        public string TimeslotCode { get; set; }
        public string GradeLevel { get; set; }
        public string Section { get; set; }
        public Nullable<System.TimeSpan> TimeStart { get; set; }
        public Nullable<System.TimeSpan> TimeEnd { get; set; }
        public string Days { get; set; }
        public string RoomNumber { get; set; }
        public string BuildingCode { get; set; }
        public Nullable<int> Capacity { get; set; }
        public string Fullname_fml { get; set; }
    }
}
