//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSARDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fee()
        {
            this.PaymentDetails = new HashSet<PaymentDetail>();
            this.StudentAssessments = new HashSet<StudentAssessment>();
            this.ScholarshipDiscounts = new HashSet<ScholarshipDiscount>();
        }
    
        public string FeeCode { get; set; }
        public string Unit { get; set; }
        public string FeeDescription { get; set; }
        public bool Deactivated { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> DateSet { get; set; }
        public string SYImplemented { get; set; }
        public string GradeLevel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
        public virtual GradeLevel GradeLevel1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentAssessment> StudentAssessments { get; set; }
        public virtual SchoolYear SchoolYear { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ScholarshipDiscount> ScholarshipDiscounts { get; set; }
    }
}
