//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSARDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentList
    {
        public string studentid { get; set; }
        public string lastname { get; set; }
        public string firstname { get; set; }
        public string middlename { get; set; }
        public string Fullname_fml { get; set; }
        public string Fullname_lmf { get; set; }
        public string GradeLevel { get; set; }
        public Nullable<int> GradeSectionCode { get; set; }
        public string SY { get; set; }
    }
}
