//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eSAR.TeacherServiceRef {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Teacher", Namespace="http://schemas.datacontract.org/2004/07/eSARService")]
    [System.SerializableAttribute()]
    public partial class Teacher : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BloodTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CivilStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfAppointmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeactivatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DialectSpokenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmploymentStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HeightCmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ImageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobileNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PAMunicipalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PAProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PARegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PAStreetNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PERAAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string POBMunicipalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string POBProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PagIBIGNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhilHealthNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PreviousSchoolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RAMunicipalityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RAProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RARegionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RAStreetNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResTelephoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SSSNumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpouseBusinessAddField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpouseEmployerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpouseFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpouseLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpouseMiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpouseOccupationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SpouseTelephoneNoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eSAR.TeacherServiceRef.TeacherChildren[] TeacherChildrensField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eSAR.TeacherServiceRef.TeacherEducationalBackground[] TeacherEducationalBackgroundsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eSAR.TeacherServiceRef.TeacherEligibility[] TeacherEligibilitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eSAR.TeacherServiceRef.TrainingSeminar[] TrainingSeminarsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double WeightKgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eSAR.TeacherServiceRef.WorkExperience[] WorkExperiencesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BloodType {
            get {
                return this.BloodTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.BloodTypeField, value) != true)) {
                    this.BloodTypeField = value;
                    this.RaisePropertyChanged("BloodType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CivilStatus {
            get {
                return this.CivilStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.CivilStatusField, value) != true)) {
                    this.CivilStatusField = value;
                    this.RaisePropertyChanged("CivilStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((this.DOBField.Equals(value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfAppointment {
            get {
                return this.DateOfAppointmentField;
            }
            set {
                if ((this.DateOfAppointmentField.Equals(value) != true)) {
                    this.DateOfAppointmentField = value;
                    this.RaisePropertyChanged("DateOfAppointment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deactivated {
            get {
                return this.DeactivatedField;
            }
            set {
                if ((this.DeactivatedField.Equals(value) != true)) {
                    this.DeactivatedField = value;
                    this.RaisePropertyChanged("Deactivated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DialectSpoken {
            get {
                return this.DialectSpokenField;
            }
            set {
                if ((object.ReferenceEquals(this.DialectSpokenField, value) != true)) {
                    this.DialectSpokenField = value;
                    this.RaisePropertyChanged("DialectSpoken");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddress {
            get {
                return this.EmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddressField, value) != true)) {
                    this.EmailAddressField = value;
                    this.RaisePropertyChanged("EmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmploymentStatus {
            get {
                return this.EmploymentStatusField;
            }
            set {
                if ((object.ReferenceEquals(this.EmploymentStatusField, value) != true)) {
                    this.EmploymentStatusField = value;
                    this.RaisePropertyChanged("EmploymentStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender {
            get {
                return this.GenderField;
            }
            set {
                if ((object.ReferenceEquals(this.GenderField, value) != true)) {
                    this.GenderField = value;
                    this.RaisePropertyChanged("Gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HeightCm {
            get {
                return this.HeightCmField;
            }
            set {
                if ((this.HeightCmField.Equals(value) != true)) {
                    this.HeightCmField = value;
                    this.RaisePropertyChanged("HeightCm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Image {
            get {
                return this.ImageField;
            }
            set {
                if ((object.ReferenceEquals(this.ImageField, value) != true)) {
                    this.ImageField = value;
                    this.RaisePropertyChanged("Image");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNo {
            get {
                return this.MobileNoField;
            }
            set {
                if ((object.ReferenceEquals(this.MobileNoField, value) != true)) {
                    this.MobileNoField = value;
                    this.RaisePropertyChanged("MobileNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PAMunicipality {
            get {
                return this.PAMunicipalityField;
            }
            set {
                if ((object.ReferenceEquals(this.PAMunicipalityField, value) != true)) {
                    this.PAMunicipalityField = value;
                    this.RaisePropertyChanged("PAMunicipality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PAProvince {
            get {
                return this.PAProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.PAProvinceField, value) != true)) {
                    this.PAProvinceField = value;
                    this.RaisePropertyChanged("PAProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PARegion {
            get {
                return this.PARegionField;
            }
            set {
                if ((object.ReferenceEquals(this.PARegionField, value) != true)) {
                    this.PARegionField = value;
                    this.RaisePropertyChanged("PARegion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PAStreetName {
            get {
                return this.PAStreetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PAStreetNameField, value) != true)) {
                    this.PAStreetNameField = value;
                    this.RaisePropertyChanged("PAStreetName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PERAA {
            get {
                return this.PERAAField;
            }
            set {
                if ((object.ReferenceEquals(this.PERAAField, value) != true)) {
                    this.PERAAField = value;
                    this.RaisePropertyChanged("PERAA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string POBMunicipality {
            get {
                return this.POBMunicipalityField;
            }
            set {
                if ((object.ReferenceEquals(this.POBMunicipalityField, value) != true)) {
                    this.POBMunicipalityField = value;
                    this.RaisePropertyChanged("POBMunicipality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string POBProvince {
            get {
                return this.POBProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.POBProvinceField, value) != true)) {
                    this.POBProvinceField = value;
                    this.RaisePropertyChanged("POBProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PagIBIGNo {
            get {
                return this.PagIBIGNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PagIBIGNoField, value) != true)) {
                    this.PagIBIGNoField = value;
                    this.RaisePropertyChanged("PagIBIGNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhilHealthNo {
            get {
                return this.PhilHealthNoField;
            }
            set {
                if ((object.ReferenceEquals(this.PhilHealthNoField, value) != true)) {
                    this.PhilHealthNoField = value;
                    this.RaisePropertyChanged("PhilHealthNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreviousSchool {
            get {
                return this.PreviousSchoolField;
            }
            set {
                if ((object.ReferenceEquals(this.PreviousSchoolField, value) != true)) {
                    this.PreviousSchoolField = value;
                    this.RaisePropertyChanged("PreviousSchool");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RAMunicipality {
            get {
                return this.RAMunicipalityField;
            }
            set {
                if ((object.ReferenceEquals(this.RAMunicipalityField, value) != true)) {
                    this.RAMunicipalityField = value;
                    this.RaisePropertyChanged("RAMunicipality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RAProvince {
            get {
                return this.RAProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.RAProvinceField, value) != true)) {
                    this.RAProvinceField = value;
                    this.RaisePropertyChanged("RAProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RARegion {
            get {
                return this.RARegionField;
            }
            set {
                if ((object.ReferenceEquals(this.RARegionField, value) != true)) {
                    this.RARegionField = value;
                    this.RaisePropertyChanged("RARegion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RAStreetName {
            get {
                return this.RAStreetNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RAStreetNameField, value) != true)) {
                    this.RAStreetNameField = value;
                    this.RaisePropertyChanged("RAStreetName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ResTelephoneNo {
            get {
                return this.ResTelephoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.ResTelephoneNoField, value) != true)) {
                    this.ResTelephoneNoField = value;
                    this.RaisePropertyChanged("ResTelephoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SSSNum {
            get {
                return this.SSSNumField;
            }
            set {
                if ((object.ReferenceEquals(this.SSSNumField, value) != true)) {
                    this.SSSNumField = value;
                    this.RaisePropertyChanged("SSSNum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpouseBusinessAdd {
            get {
                return this.SpouseBusinessAddField;
            }
            set {
                if ((object.ReferenceEquals(this.SpouseBusinessAddField, value) != true)) {
                    this.SpouseBusinessAddField = value;
                    this.RaisePropertyChanged("SpouseBusinessAdd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpouseEmployerName {
            get {
                return this.SpouseEmployerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SpouseEmployerNameField, value) != true)) {
                    this.SpouseEmployerNameField = value;
                    this.RaisePropertyChanged("SpouseEmployerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpouseFirstName {
            get {
                return this.SpouseFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SpouseFirstNameField, value) != true)) {
                    this.SpouseFirstNameField = value;
                    this.RaisePropertyChanged("SpouseFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpouseLastName {
            get {
                return this.SpouseLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SpouseLastNameField, value) != true)) {
                    this.SpouseLastNameField = value;
                    this.RaisePropertyChanged("SpouseLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpouseMiddleName {
            get {
                return this.SpouseMiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SpouseMiddleNameField, value) != true)) {
                    this.SpouseMiddleNameField = value;
                    this.RaisePropertyChanged("SpouseMiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpouseOccupation {
            get {
                return this.SpouseOccupationField;
            }
            set {
                if ((object.ReferenceEquals(this.SpouseOccupationField, value) != true)) {
                    this.SpouseOccupationField = value;
                    this.RaisePropertyChanged("SpouseOccupation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpouseTelephoneNo {
            get {
                return this.SpouseTelephoneNoField;
            }
            set {
                if ((object.ReferenceEquals(this.SpouseTelephoneNoField, value) != true)) {
                    this.SpouseTelephoneNoField = value;
                    this.RaisePropertyChanged("SpouseTelephoneNo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIN {
            get {
                return this.TINField;
            }
            set {
                if ((object.ReferenceEquals(this.TINField, value) != true)) {
                    this.TINField = value;
                    this.RaisePropertyChanged("TIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eSAR.TeacherServiceRef.TeacherChildren[] TeacherChildrens {
            get {
                return this.TeacherChildrensField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherChildrensField, value) != true)) {
                    this.TeacherChildrensField = value;
                    this.RaisePropertyChanged("TeacherChildrens");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eSAR.TeacherServiceRef.TeacherEducationalBackground[] TeacherEducationalBackgrounds {
            get {
                return this.TeacherEducationalBackgroundsField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherEducationalBackgroundsField, value) != true)) {
                    this.TeacherEducationalBackgroundsField = value;
                    this.RaisePropertyChanged("TeacherEducationalBackgrounds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eSAR.TeacherServiceRef.TeacherEligibility[] TeacherEligibilities {
            get {
                return this.TeacherEligibilitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherEligibilitiesField, value) != true)) {
                    this.TeacherEligibilitiesField = value;
                    this.RaisePropertyChanged("TeacherEligibilities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherId {
            get {
                return this.TeacherIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherIdField, value) != true)) {
                    this.TeacherIdField = value;
                    this.RaisePropertyChanged("TeacherId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eSAR.TeacherServiceRef.TrainingSeminar[] TrainingSeminars {
            get {
                return this.TrainingSeminarsField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainingSeminarsField, value) != true)) {
                    this.TrainingSeminarsField = value;
                    this.RaisePropertyChanged("TrainingSeminars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double WeightKg {
            get {
                return this.WeightKgField;
            }
            set {
                if ((this.WeightKgField.Equals(value) != true)) {
                    this.WeightKgField = value;
                    this.RaisePropertyChanged("WeightKg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eSAR.TeacherServiceRef.WorkExperience[] WorkExperiences {
            get {
                return this.WorkExperiencesField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkExperiencesField, value) != true)) {
                    this.WorkExperiencesField = value;
                    this.RaisePropertyChanged("WorkExperiences");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeacherChildren", Namespace="http://schemas.datacontract.org/2004/07/eSARService")]
    [System.SerializableAttribute()]
    public partial class TeacherChildren : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ChildIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DOBField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ChildId {
            get {
                return this.ChildIdField;
            }
            set {
                if ((this.ChildIdField.Equals(value) != true)) {
                    this.ChildIdField = value;
                    this.RaisePropertyChanged("ChildId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DOB {
            get {
                return this.DOBField;
            }
            set {
                if ((this.DOBField.Equals(value) != true)) {
                    this.DOBField = value;
                    this.RaisePropertyChanged("DOB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherId {
            get {
                return this.TeacherIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherIdField, value) != true)) {
                    this.TeacherIdField = value;
                    this.RaisePropertyChanged("TeacherId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeacherEducationalBackground", Namespace="http://schemas.datacontract.org/2004/07/eSARService")]
    [System.SerializableAttribute()]
    public partial class TeacherEducationalBackground : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CourseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool DeactivatedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EducLevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HonorsReceivedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameOfSchoolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TEBIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TEBYearFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TEBYearToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Course {
            get {
                return this.CourseField;
            }
            set {
                if ((object.ReferenceEquals(this.CourseField, value) != true)) {
                    this.CourseField = value;
                    this.RaisePropertyChanged("Course");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Deactivated {
            get {
                return this.DeactivatedField;
            }
            set {
                if ((this.DeactivatedField.Equals(value) != true)) {
                    this.DeactivatedField = value;
                    this.RaisePropertyChanged("Deactivated");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EducLevel {
            get {
                return this.EducLevelField;
            }
            set {
                if ((object.ReferenceEquals(this.EducLevelField, value) != true)) {
                    this.EducLevelField = value;
                    this.RaisePropertyChanged("EducLevel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HonorsReceived {
            get {
                return this.HonorsReceivedField;
            }
            set {
                if ((object.ReferenceEquals(this.HonorsReceivedField, value) != true)) {
                    this.HonorsReceivedField = value;
                    this.RaisePropertyChanged("HonorsReceived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NameOfSchool {
            get {
                return this.NameOfSchoolField;
            }
            set {
                if ((object.ReferenceEquals(this.NameOfSchoolField, value) != true)) {
                    this.NameOfSchoolField = value;
                    this.RaisePropertyChanged("NameOfSchool");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TEBId {
            get {
                return this.TEBIdField;
            }
            set {
                if ((this.TEBIdField.Equals(value) != true)) {
                    this.TEBIdField = value;
                    this.RaisePropertyChanged("TEBId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TEBYearFrom {
            get {
                return this.TEBYearFromField;
            }
            set {
                if ((this.TEBYearFromField.Equals(value) != true)) {
                    this.TEBYearFromField = value;
                    this.RaisePropertyChanged("TEBYearFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TEBYearTo {
            get {
                return this.TEBYearToField;
            }
            set {
                if ((this.TEBYearToField.Equals(value) != true)) {
                    this.TEBYearToField = value;
                    this.RaisePropertyChanged("TEBYearTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherId {
            get {
                return this.TeacherIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherIdField, value) != true)) {
                    this.TeacherIdField = value;
                    this.RaisePropertyChanged("TeacherId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TeacherEligibility", Namespace="http://schemas.datacontract.org/2004/07/eSARService")]
    [System.SerializableAttribute()]
    public partial class TeacherEligibility : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfExamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EligibilityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EligibilityIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime IssueDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LicenseNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceOfExamField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RatingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfExam {
            get {
                return this.DateOfExamField;
            }
            set {
                if ((this.DateOfExamField.Equals(value) != true)) {
                    this.DateOfExamField = value;
                    this.RaisePropertyChanged("DateOfExam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Eligibility {
            get {
                return this.EligibilityField;
            }
            set {
                if ((object.ReferenceEquals(this.EligibilityField, value) != true)) {
                    this.EligibilityField = value;
                    this.RaisePropertyChanged("Eligibility");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EligibilityId {
            get {
                return this.EligibilityIdField;
            }
            set {
                if ((this.EligibilityIdField.Equals(value) != true)) {
                    this.EligibilityIdField = value;
                    this.RaisePropertyChanged("EligibilityId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime IssueDate {
            get {
                return this.IssueDateField;
            }
            set {
                if ((this.IssueDateField.Equals(value) != true)) {
                    this.IssueDateField = value;
                    this.RaisePropertyChanged("IssueDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LicenseNumber {
            get {
                return this.LicenseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.LicenseNumberField, value) != true)) {
                    this.LicenseNumberField = value;
                    this.RaisePropertyChanged("LicenseNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlaceOfExam {
            get {
                return this.PlaceOfExamField;
            }
            set {
                if ((object.ReferenceEquals(this.PlaceOfExamField, value) != true)) {
                    this.PlaceOfExamField = value;
                    this.RaisePropertyChanged("PlaceOfExam");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Rating {
            get {
                return this.RatingField;
            }
            set {
                if ((object.ReferenceEquals(this.RatingField, value) != true)) {
                    this.RatingField = value;
                    this.RaisePropertyChanged("Rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherId {
            get {
                return this.TeacherIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherIdField, value) != true)) {
                    this.TeacherIdField = value;
                    this.RaisePropertyChanged("TeacherId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TrainingSeminar", Namespace="http://schemas.datacontract.org/2004/07/eSARService")]
    [System.SerializableAttribute()]
    public partial class TrainingSeminar : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AreaOfTrainingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ConductedByField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateToField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double NoOfHoursField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TSIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AreaOfTraining {
            get {
                return this.AreaOfTrainingField;
            }
            set {
                if ((object.ReferenceEquals(this.AreaOfTrainingField, value) != true)) {
                    this.AreaOfTrainingField = value;
                    this.RaisePropertyChanged("AreaOfTraining");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ConductedBy {
            get {
                return this.ConductedByField;
            }
            set {
                if ((object.ReferenceEquals(this.ConductedByField, value) != true)) {
                    this.ConductedByField = value;
                    this.RaisePropertyChanged("ConductedBy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateFrom {
            get {
                return this.DateFromField;
            }
            set {
                if ((this.DateFromField.Equals(value) != true)) {
                    this.DateFromField = value;
                    this.RaisePropertyChanged("DateFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTo {
            get {
                return this.DateToField;
            }
            set {
                if ((this.DateToField.Equals(value) != true)) {
                    this.DateToField = value;
                    this.RaisePropertyChanged("DateTo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double NoOfHours {
            get {
                return this.NoOfHoursField;
            }
            set {
                if ((this.NoOfHoursField.Equals(value) != true)) {
                    this.NoOfHoursField = value;
                    this.RaisePropertyChanged("NoOfHours");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TSID {
            get {
                return this.TSIDField;
            }
            set {
                if ((this.TSIDField.Equals(value) != true)) {
                    this.TSIDField = value;
                    this.RaisePropertyChanged("TSID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherId {
            get {
                return this.TeacherIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherIdField, value) != true)) {
                    this.TeacherIdField = value;
                    this.RaisePropertyChanged("TeacherId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkExperience", Namespace="http://schemas.datacontract.org/2004/07/eSARService")]
    [System.SerializableAttribute()]
    public partial class WorkExperience : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double MonthlySalaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusOfEmploymentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeacherIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WEIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime WorkExpFromField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime WorkExpToField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MonthlySalary {
            get {
                return this.MonthlySalaryField;
            }
            set {
                if ((this.MonthlySalaryField.Equals(value) != true)) {
                    this.MonthlySalaryField = value;
                    this.RaisePropertyChanged("MonthlySalary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusOfEmployment {
            get {
                return this.StatusOfEmploymentField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusOfEmploymentField, value) != true)) {
                    this.StatusOfEmploymentField = value;
                    this.RaisePropertyChanged("StatusOfEmployment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeacherId {
            get {
                return this.TeacherIdField;
            }
            set {
                if ((object.ReferenceEquals(this.TeacherIdField, value) != true)) {
                    this.TeacherIdField = value;
                    this.RaisePropertyChanged("TeacherId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WEId {
            get {
                return this.WEIdField;
            }
            set {
                if ((this.WEIdField.Equals(value) != true)) {
                    this.WEIdField = value;
                    this.RaisePropertyChanged("WEId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime WorkExpFrom {
            get {
                return this.WorkExpFromField;
            }
            set {
                if ((this.WorkExpFromField.Equals(value) != true)) {
                    this.WorkExpFromField = value;
                    this.RaisePropertyChanged("WorkExpFrom");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime WorkExpTo {
            get {
                return this.WorkExpToField;
            }
            set {
                if ((this.WorkExpToField.Equals(value) != true)) {
                    this.WorkExpToField = value;
                    this.RaisePropertyChanged("WorkExpTo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TeacherServiceRef.ITeacherService")]
    public interface ITeacherService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/CreateTeacher", ReplyAction="http://tempuri.org/ITeacherService/CreateTeacherResponse")]
        eSAR.TeacherServiceRef.CreateTeacherResponse CreateTeacher(eSAR.TeacherServiceRef.CreateTeacherRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/CreateTeacher", ReplyAction="http://tempuri.org/ITeacherService/CreateTeacherResponse")]
        System.Threading.Tasks.Task<eSAR.TeacherServiceRef.CreateTeacherResponse> CreateTeacherAsync(eSAR.TeacherServiceRef.CreateTeacherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/UpdateTeacher", ReplyAction="http://tempuri.org/ITeacherService/UpdateTeacherResponse")]
        eSAR.TeacherServiceRef.UpdateTeacherResponse UpdateTeacher(eSAR.TeacherServiceRef.UpdateTeacherRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/UpdateTeacher", ReplyAction="http://tempuri.org/ITeacherService/UpdateTeacherResponse")]
        System.Threading.Tasks.Task<eSAR.TeacherServiceRef.UpdateTeacherResponse> UpdateTeacherAsync(eSAR.TeacherServiceRef.UpdateTeacherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/GetAllTeachers", ReplyAction="http://tempuri.org/ITeacherService/GetAllTeachersResponse")]
        eSAR.TeacherServiceRef.Teacher[] GetAllTeachers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/GetAllTeachers", ReplyAction="http://tempuri.org/ITeacherService/GetAllTeachersResponse")]
        System.Threading.Tasks.Task<eSAR.TeacherServiceRef.Teacher[]> GetAllTeachersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/GetFilteredTeachers", ReplyAction="http://tempuri.org/ITeacherService/GetFilteredTeachersResponse")]
        eSAR.TeacherServiceRef.Teacher[] GetFilteredTeachers(string searchType, string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/GetFilteredTeachers", ReplyAction="http://tempuri.org/ITeacherService/GetFilteredTeachersResponse")]
        System.Threading.Tasks.Task<eSAR.TeacherServiceRef.Teacher[]> GetFilteredTeachersAsync(string searchType, string search);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/GetTeacher", ReplyAction="http://tempuri.org/ITeacherService/GetTeacherResponse")]
        eSAR.TeacherServiceRef.GetTeacherResponse GetTeacher(eSAR.TeacherServiceRef.GetTeacherRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/GetTeacher", ReplyAction="http://tempuri.org/ITeacherService/GetTeacherResponse")]
        System.Threading.Tasks.Task<eSAR.TeacherServiceRef.GetTeacherResponse> GetTeacherAsync(eSAR.TeacherServiceRef.GetTeacherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/DeactivateTeacher", ReplyAction="http://tempuri.org/ITeacherService/DeactivateTeacherResponse")]
        eSAR.TeacherServiceRef.DeactivateTeacherResponse DeactivateTeacher(eSAR.TeacherServiceRef.DeactivateTeacherRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/DeactivateTeacher", ReplyAction="http://tempuri.org/ITeacherService/DeactivateTeacherResponse")]
        System.Threading.Tasks.Task<eSAR.TeacherServiceRef.DeactivateTeacherResponse> DeactivateTeacherAsync(eSAR.TeacherServiceRef.DeactivateTeacherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/GenerateTeacherId", ReplyAction="http://tempuri.org/ITeacherService/GenerateTeacherIdResponse")]
        string GenerateTeacherId();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITeacherService/GenerateTeacherId", ReplyAction="http://tempuri.org/ITeacherService/GenerateTeacherIdResponse")]
        System.Threading.Tasks.Task<string> GenerateTeacherIdAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateTeacher", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateTeacherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public eSAR.TeacherServiceRef.Teacher teacher;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public CreateTeacherRequest() {
        }
        
        public CreateTeacherRequest(eSAR.TeacherServiceRef.Teacher teacher, string message) {
            this.teacher = teacher;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateTeacherResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class CreateTeacherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool CreateTeacherResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public eSAR.TeacherServiceRef.Teacher teacher;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string message;
        
        public CreateTeacherResponse() {
        }
        
        public CreateTeacherResponse(bool CreateTeacherResult, eSAR.TeacherServiceRef.Teacher teacher, string message) {
            this.CreateTeacherResult = CreateTeacherResult;
            this.teacher = teacher;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateTeacher", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateTeacherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public eSAR.TeacherServiceRef.Teacher teacher;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public UpdateTeacherRequest() {
        }
        
        public UpdateTeacherRequest(eSAR.TeacherServiceRef.Teacher teacher, string message) {
            this.teacher = teacher;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateTeacherResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class UpdateTeacherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool UpdateTeacherResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public eSAR.TeacherServiceRef.Teacher teacher;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string message;
        
        public UpdateTeacherResponse() {
        }
        
        public UpdateTeacherResponse(bool UpdateTeacherResult, eSAR.TeacherServiceRef.Teacher teacher, string message) {
            this.UpdateTeacherResult = UpdateTeacherResult;
            this.teacher = teacher;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTeacher", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTeacherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string teacherId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public GetTeacherRequest() {
        }
        
        public GetTeacherRequest(string teacherId, string message) {
            this.teacherId = teacherId;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetTeacherResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetTeacherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public eSAR.TeacherServiceRef.Teacher GetTeacherResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public GetTeacherResponse() {
        }
        
        public GetTeacherResponse(eSAR.TeacherServiceRef.Teacher GetTeacherResult, string message) {
            this.GetTeacherResult = GetTeacherResult;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeactivateTeacher", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeactivateTeacherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string teacherId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public DeactivateTeacherRequest() {
        }
        
        public DeactivateTeacherRequest(string teacherId, string message) {
            this.teacherId = teacherId;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DeactivateTeacherResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class DeactivateTeacherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool DeactivateTeacherResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string message;
        
        public DeactivateTeacherResponse() {
        }
        
        public DeactivateTeacherResponse(bool DeactivateTeacherResult, string message) {
            this.DeactivateTeacherResult = DeactivateTeacherResult;
            this.message = message;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITeacherServiceChannel : eSAR.TeacherServiceRef.ITeacherService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TeacherServiceClient : System.ServiceModel.ClientBase<eSAR.TeacherServiceRef.ITeacherService>, eSAR.TeacherServiceRef.ITeacherService {
        
        public TeacherServiceClient() {
        }
        
        public TeacherServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TeacherServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeacherServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TeacherServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSAR.TeacherServiceRef.CreateTeacherResponse eSAR.TeacherServiceRef.ITeacherService.CreateTeacher(eSAR.TeacherServiceRef.CreateTeacherRequest request) {
            return base.Channel.CreateTeacher(request);
        }
        
        public bool CreateTeacher(ref eSAR.TeacherServiceRef.Teacher teacher, ref string message) {
            eSAR.TeacherServiceRef.CreateTeacherRequest inValue = new eSAR.TeacherServiceRef.CreateTeacherRequest();
            inValue.teacher = teacher;
            inValue.message = message;
            eSAR.TeacherServiceRef.CreateTeacherResponse retVal = ((eSAR.TeacherServiceRef.ITeacherService)(this)).CreateTeacher(inValue);
            teacher = retVal.teacher;
            message = retVal.message;
            return retVal.CreateTeacherResult;
        }
        
        public System.Threading.Tasks.Task<eSAR.TeacherServiceRef.CreateTeacherResponse> CreateTeacherAsync(eSAR.TeacherServiceRef.CreateTeacherRequest request) {
            return base.Channel.CreateTeacherAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSAR.TeacherServiceRef.UpdateTeacherResponse eSAR.TeacherServiceRef.ITeacherService.UpdateTeacher(eSAR.TeacherServiceRef.UpdateTeacherRequest request) {
            return base.Channel.UpdateTeacher(request);
        }
        
        public bool UpdateTeacher(ref eSAR.TeacherServiceRef.Teacher teacher, ref string message) {
            eSAR.TeacherServiceRef.UpdateTeacherRequest inValue = new eSAR.TeacherServiceRef.UpdateTeacherRequest();
            inValue.teacher = teacher;
            inValue.message = message;
            eSAR.TeacherServiceRef.UpdateTeacherResponse retVal = ((eSAR.TeacherServiceRef.ITeacherService)(this)).UpdateTeacher(inValue);
            teacher = retVal.teacher;
            message = retVal.message;
            return retVal.UpdateTeacherResult;
        }
        
        public System.Threading.Tasks.Task<eSAR.TeacherServiceRef.UpdateTeacherResponse> UpdateTeacherAsync(eSAR.TeacherServiceRef.UpdateTeacherRequest request) {
            return base.Channel.UpdateTeacherAsync(request);
        }
        
        public eSAR.TeacherServiceRef.Teacher[] GetAllTeachers() {
            return base.Channel.GetAllTeachers();
        }
        
        public System.Threading.Tasks.Task<eSAR.TeacherServiceRef.Teacher[]> GetAllTeachersAsync() {
            return base.Channel.GetAllTeachersAsync();
        }
        
        public eSAR.TeacherServiceRef.Teacher[] GetFilteredTeachers(string searchType, string search) {
            return base.Channel.GetFilteredTeachers(searchType, search);
        }
        
        public System.Threading.Tasks.Task<eSAR.TeacherServiceRef.Teacher[]> GetFilteredTeachersAsync(string searchType, string search) {
            return base.Channel.GetFilteredTeachersAsync(searchType, search);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSAR.TeacherServiceRef.GetTeacherResponse eSAR.TeacherServiceRef.ITeacherService.GetTeacher(eSAR.TeacherServiceRef.GetTeacherRequest request) {
            return base.Channel.GetTeacher(request);
        }
        
        public eSAR.TeacherServiceRef.Teacher GetTeacher(string teacherId, ref string message) {
            eSAR.TeacherServiceRef.GetTeacherRequest inValue = new eSAR.TeacherServiceRef.GetTeacherRequest();
            inValue.teacherId = teacherId;
            inValue.message = message;
            eSAR.TeacherServiceRef.GetTeacherResponse retVal = ((eSAR.TeacherServiceRef.ITeacherService)(this)).GetTeacher(inValue);
            message = retVal.message;
            return retVal.GetTeacherResult;
        }
        
        public System.Threading.Tasks.Task<eSAR.TeacherServiceRef.GetTeacherResponse> GetTeacherAsync(eSAR.TeacherServiceRef.GetTeacherRequest request) {
            return base.Channel.GetTeacherAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        eSAR.TeacherServiceRef.DeactivateTeacherResponse eSAR.TeacherServiceRef.ITeacherService.DeactivateTeacher(eSAR.TeacherServiceRef.DeactivateTeacherRequest request) {
            return base.Channel.DeactivateTeacher(request);
        }
        
        public bool DeactivateTeacher(string teacherId, ref string message) {
            eSAR.TeacherServiceRef.DeactivateTeacherRequest inValue = new eSAR.TeacherServiceRef.DeactivateTeacherRequest();
            inValue.teacherId = teacherId;
            inValue.message = message;
            eSAR.TeacherServiceRef.DeactivateTeacherResponse retVal = ((eSAR.TeacherServiceRef.ITeacherService)(this)).DeactivateTeacher(inValue);
            message = retVal.message;
            return retVal.DeactivateTeacherResult;
        }
        
        public System.Threading.Tasks.Task<eSAR.TeacherServiceRef.DeactivateTeacherResponse> DeactivateTeacherAsync(eSAR.TeacherServiceRef.DeactivateTeacherRequest request) {
            return base.Channel.DeactivateTeacherAsync(request);
        }
        
        public string GenerateTeacherId() {
            return base.Channel.GenerateTeacherId();
        }
        
        public System.Threading.Tasks.Task<string> GenerateTeacherIdAsync() {
            return base.Channel.GenerateTeacherIdAsync();
        }
    }
}
